apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:A8OBeEcIghlT//ZoiSUI0Q/xVOImYContKlP9oIyvSAOH1t/293jSMcRCS8=,iv:YFSP8GyAYFOuMlMNz3S8cyswh7/NWmi8zbi0n/N7jj4=,tag:bAJZufx1/2LmEgX6yNsxDg==,type:str]
    admin-user: ENC[AES256_GCM,data:Zynb7HIyNa3PjCo6o0C6QlSMmng=,iv:r5XhfMXHUqSWVKnQo1ttic+HT9ckFo7rRBga58f+M/s=,tag:+Rc+BpHeS7dh49nE7KCFzA==,type:str]
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBicWNIMGlYMG55WjF3SXlo
            WjB0VjRXYVNFa0V5dXREeHdwZ3M0bTAxcldrCmpTZnhhdXhkSFphR2dMd2ptZmhx
            YmZSVHlnY1I1bkdhSllwNElkSU1CZ28KLS0tIGdkc3l3QzhGTEM2WlN6T0VmV2pH
            dUo5dXZGdUZSekE5OENOcHBFdmhYblEK3zq9DaQ48smpFwocP90fltcKOeRQtQvu
            W9nkzEaP9mzHilLyDuTw+T9UJAku843cS2x6ngPRB5s9iR63xAd56w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ruzv8k3s30akc8tesmkg5mm92rppddq6cps2xtxvg74lt23x64uqq05d7w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-11T04:12:38Z"
    mac: ENC[AES256_GCM,data:KgTuAOqZ+4CXqZHvKn5X35j8tIdM63vrXiSh0/rK9wLBzKg6AzKMdFFA+9UK5u2EgfTNGvc1yJKLpVCW4NMh2vo3pc19pwvN+OLFTQdfBrbSonPGJl8cFLVi5ysrYSbMvKRdWfXHrDJdipwpjJxlvBGsZKkDER1k6dG7/jY5gLI=,iv:1x0NnHqu7XZOyibh/EDxB/IEOdvs3b3C0QJKm8advoM=,tag:sMUD5q0ov9+ujwCIqleuhA==,type:str]
    version: 3.13.1
