apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - grafana-admin.sops.yaml
  - helmrepositories.yaml
  - kube-prometheus-stack.yaml
  - loki.yaml
  - alloy.yaml

configMapGenerator:
  - name: grafana-dashboard-pods
    namespace: monitoring
    files:
      - dashboards/pods.json
    options:
      labels:
        grafana_dashboard: "1"

