- Developer:
    - HackerNews:
        - href: https://www.hckrnws.com
    - Github:
        - href: https://github.com/xgabrielmorales
    - Syncthing:
        - href: https://syncthing.xgabrielmorales.com
    - Grafana:
        - href: https://grafana.xgabrielmorales.com
    - DDNS:
        - href: https://dns.xgabrielmorales.com
    - Portainer:
        - href: https://portainer.xgabrielmorales.com

- Social:
    - ProtonMail:
        - href: https://mail.proton.me/u/0/inbox
    - Whatsapp:
        - href: https://web.whatsapp.com
    - Discord:
        - href: https://discord.com/app
    - Reddit:
        - href: https://reddit.xgabrielmorales.com

- Entertainment:
    - Invidious:
        - href: https://invidious.xgabrielmorales.com
    - Spotify:
        - href: https://open.spotify.com
    - Dumb:
        - href: https://dumb.xgabrielmorales.com
