- Servers:
    - Portainer:
        icon: sh-portainer.svg
        href: "https://portainer.xgabrielmorales.com/"
        widget:
          type: portainer
          url: "{{HOMEPAGE_VAR_PORTAINER_URL}}"
          env: "{{HOMEPAGE_VAR_PORTAINER_ENV}}"
          key: "{{HOMEPAGE_VAR_PORTAINTER_KEY}}"
    - Traefik:
        icon: sh-traefik.svg
        href: "https://traefik.xgabrielmorales.com/"
        widget:
          type: traefik
          url: "{{HOMEPAGE_VAR_TRAEFIK_URL}}"

- Networking:
    - Pi-hole:
        icon: sh-pi-hole.svg
        href: "https://pihole.xgabrielmorales.com/admin"
        widget:
          type: pihole
          version: 6
          url: "{{HOMEPAGE_VAR_PIHOLE_URL}}"
          key: "{{HOMEPAGE_VAR_PIHOLE_KEY}}"
    - MySpeed:
        icon: sh-myspeed.webp
        href: "https://speed.xgabrielmorales.com"
        widget:
          type: myspeed
          url: "{{HOMEPAGE_VAR_MYSPEED_URL}}"
