- name: Home
  columns:
    - size: small
      widgets:
        - type: clock
          hour-format: 24h

        - type: monitor
          cache: 1m
          title: Selfhosted Services
          style: compact
          sites:
            - title: DDNS Updater
              url: https://dns.xgabrielmorales.com
            - title: Dumb
              url: https://dumb.xgabrielmorales.com
            - title: File Manager
              url: https://filebrowser.xgabrielmorales.com
            - title: Forgejo
              url: https://git.xgabrielmorales.com
            - title: Grafana
              url: https://grafana.xgabrielmorales.com
            - title: Invidious
              url: https://invidious.xgabrielmorales.com/preferences
            - title: Jellyfin
              url: https://jellyfin.xgabrielmorales.com
            - title: Myspeed
              url: https://speed.xgabrielmorales.com
            - title: qBittorrent
              url: https://qbittorrent.xgabrielmorales.com
            - title: Redlib
              url: https://redlib.xgabrielmorales.com/settings
            - title: Swarmpit
              url: https://swarmpit.xgabrielmorales.com
            - title: Syncthing
              url: https://syncthing.xgabrielmorales.com
            - title: Technitium
              url: https://technitium.xgabrielmorales.com
            - title: Wireguard
              url: https://wg.xgabrielmorales.com

    - size: full
      widgets:
        - type: search
          search-engine: duckduckgo

        - type: hacker-news
          comments-url-template: https://www.hckrnws.com/stories/{POST-ID}

        - type: group
          widgets:
            - type: reddit
              subreddit: selfhosted
              show-thumbnails: false

    - size: small
      widgets:
        - type: calendar
          first-day-of-week: monday

        - type: bookmarks
          groups:
            - title: Development
              links:
                - title: Forgejo
                  url: https://git.xgabrielmorales.com
                - title: Github
                  url: https://github.com/xgabrielmorales
            - title: Entertainment
              links:
                - title: Dumb
                  url: https://dumb.xgabrielmorales.com/
                - title: Invidious
                  url: https://invidious.xgabrielmorales.com/
                - title: Jellyfin
                  url: https://jellyfin.xgabrielmorales.com/
                - title: Spotify
                  url: https://open.spotify.com/
            - title: Media
              links:
                - title: File Manager
                  url: https://filebrowser.xgabrielmorales.com/
                - title: qBittorrent
                  url: https://qbittorrent.xgabrielmorales.com/
            - title: Social
              links:
                - title: Discord
                  url: https://discord.com/app
                - title: ProtonDrive
                  url: https://drive.proton.me/u/0
                - title: ProtonMail
                  url: https://mail.proton.me/u/0/inbox
                - title: Redlib
                  url: https://redlib.xgabrielmorales.com
                - title: Whatsapp
                  url: https://web.whatsapp.com/
