services:
  renovate:
    image: renovate/renovate:44.33.2@sha256:fe47c58a918726ecb9efa7837735e2a7c6eed44e0181ab2c7b14738b84df0a21
    volumes:
      - ./config.js:/usr/src/app/config.js
    environment:
      RENOVATE_CONFIG_FILE: /usr/src/app/config.js
      RENOVATE_TOKEN: ${RENOVATE_TOKEN}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      DOCKERHUB_USERNAME: ${DOCKERHUB_USERNAME}
      DOCKERHUB_TOKEN: ${DOCKERHUB_TOKEN}
