services:
  renovate:
    image: renovate/renovate:44.14.10@sha256:26a4ced910d74c2d3dc8c1080b30704840f53206a3baede88fc579f37a2f6e45
    volumes:
      - ./config.js:/usr/src/app/config.js
    environment:
      RENOVATE_CONFIG_FILE: /usr/src/app/config.js
      RENOVATE_TOKEN: ${RENOVATE_TOKEN}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      DOCKERHUB_USERNAME: ${DOCKERHUB_USERNAME}
      DOCKERHUB_TOKEN: ${DOCKERHUB_TOKEN}
