apiVersion: v1
kind: Secret
metadata:
    name: redlib
type: Opaque
stringData:
    REDLIB_DEFAULT_FRONT_PAGE: ENC[AES256_GCM,data:uZ1X4agTXw==,iv:dqGjh9WtIw7w9Croa92D+NGsGoypByd9f5liSLp9CTM=,tag:udyrEm8oNcOyff7NpVpP7A==,type:str]
    REDLIB_DEFAULT_HIDE_AWARDS: ENC[AES256_GCM,data:pP4=,iv:IPDNIRSep9FZcXFNG0wqeZVRnMyKLOk6b7hneWjGCdY=,tag:mj6m2LL/k4JQ5YskdTJKaA==,type:str]
    REDLIB_DEFAULT_HIDE_HLS_NOTIFICATION: ENC[AES256_GCM,data:ZLQ=,iv:hrvEQoGvf1KAkv/6wHWJZzg/n48H7EWV/Up7HlVo0/w=,tag:HUmdjIhUAN6+Net76n2IlQ==,type:str]
    REDLIB_DEFAULT_HIDE_SCORE: ENC[AES256_GCM,data:GUw=,iv:ldPZQdKqWx6WJVX80lbnp8LQKrg1mJpbvJE82+NlEjY=,tag:7iKs4PkoEqUIyyX9P+k79w==,type:str]
    REDLIB_DEFAULT_HIDE_SIDEBAR_AND_SUMMARY: ENC[AES256_GCM,data:Egk=,iv:Qz+ca1ynp2LTTnUsDhtjx4V7R64Hq6RwlNqIc8pRSuI=,tag:htd2CJUt1MmYHuEmB0/uqw==,type:str]
    REDLIB_DEFAULT_LAYOUT: ENC[AES256_GCM,data:QjvhIHs=,iv:royC1aHfMXF9M1wbuBGAvL2uhtiSC0H/WRRBV9lR6iA=,tag:iy2zNaID5cP/XXV/scobNA==,type:str]
    REDLIB_DEFAULT_THEME: ENC[AES256_GCM,data:bfQLhbC5TQ==,iv:ScVSN2BRQrYewjh0C19dPLqb1auH5mszrrlPNApJs6Y=,tag:7H6OC1xq7PJvkHVqxF/7gg==,type:str]
    REDLIB_DEFAULT_USE_HLS: ENC[AES256_GCM,data:45E=,iv:U6RezKmitprQh90aQUsUvAj9Br4CRpcj6s001mMipF4=,tag:k8L68n+F/CqYbsD3wgx7qw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtNTNOMkhrNk5UVVhZSjJj
            SVN3SHM2M0FoRWpBK0pYNTdUV2w3QkFqUTJnClBCd0dzaWxUTHNyNzA4OHBXbnND
            NjdwRXNoMHRuYnl6R0FHUzZtd2FHNE0KLS0tIEd5VHMwTWNJYVdsaEdtcmkrYnNQ
            QlhuUzVoRTVaS00yaHdVaWRrZG1XMEEKwRpbLoDqCaWgM7Zmwzw4NWAtUePm8Q1d
            I3qTY6DuKxluDp/S19FJtRgUFTkaexm7tKv3Blpu8ANuF1oPiQMtuw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ruzv8k3s30akc8tesmkg5mm92rppddq6cps2xtxvg74lt23x64uqq05d7w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-16T03:38:09Z"
    mac: ENC[AES256_GCM,data:R0jXj4hOwKMv1CMWqD5sLoaWCEjTL1SL6G0UpD6+W7H5Xegu5VVjphuuxqMzZ7binkcevQ5QJ56bZaC0zMPOUQ9uGQYVIhpEALoiHyUJWv+NjHbgyplNyFFeVGWuTCr0DRzVu1rbRcUAuByO02UWiRhshuP8P1NY94dh4+bZ5vs=,iv:fRmjk5V4LH9W/qWv3wsTPzSiLLptXqUXhX5VYAyIlpA=,tag:TxNGMblsk7sYAek/lyiPRg==,type:str]
    version: 3.13.3
