apiVersion: v1
kind: Secret
metadata:
    name: redlib
type: Opaque
stringData:
    REDLIB_BANNER: ""
    REDLIB_DEFAULT_AUTOPLAY_VIDEOS: ENC[AES256_GCM,data:72Yj,iv:nm97WemQeSIAeVPTKLOVkCICd/pC0Yr3eYgK1dWs06o=,tag:5BzyNhRBbyUu1QvSpp4RnQ==,type:str]
    REDLIB_DEFAULT_BLUR_NSFW: ENC[AES256_GCM,data:zw1H,iv:bAJuN7n6DwcvAG3200ASBczF9wxELLFJXYWXJ+ALoGo=,tag:WbrUJeecRFqVy7pkKX8amA==,type:str]
    REDLIB_DEFAULT_BLUR_SPOILER: ENC[AES256_GCM,data:yKrB,iv:Shk7PWpMreDEle6Dz1FilEt/4dBq/ANQZjt956DcFZI=,tag:PZGU9+tDdknN85UL2PO8ZA==,type:str]
    REDLIB_DEFAULT_COMMENT_SORT: ENC[AES256_GCM,data:JZzi,iv:ECuBBAa51Sq2HvsuawHcACITuNU+Y/YoLD7yLJa4pr8=,tag:JHWotUNIudLqXzSuCKeUjg==,type:str]
    REDLIB_DEFAULT_DISABLE_VISIT_REDDIT_CONFIRMATION: ENC[AES256_GCM,data:QyQ=,iv:2ovU30GL360sY53YVCGKoT4ztjBod2FJtpBqQ1fDPtI=,tag:We9auoQIKQWnukEgEGdNFQ==,type:str]
    REDLIB_DEFAULT_FILTERS: ""
    REDLIB_DEFAULT_FIXED_NAVBAR: ENC[AES256_GCM,data:Prc=,iv:kZL4u0XA0o+hDdBnJ4+liTcpX9HNEVaaxEuZmXoBONs=,tag:Zo2W1IxB721b/uG5ssPFNw==,type:str]
    REDLIB_DEFAULT_FRONT_PAGE: ENC[AES256_GCM,data:uZ1X4agTXw==,iv:dqGjh9WtIw7w9Croa92D+NGsGoypByd9f5liSLp9CTM=,tag:udyrEm8oNcOyff7NpVpP7A==,type:str]
    REDLIB_DEFAULT_HIDE_AWARDS: ENC[AES256_GCM,data:APOk,iv:Dn0ysLpfjhI5cHyN04zlb5FQPk8jamOGfw39VxdXzag=,tag:3ELYkOIftwf3owuFqyr4Pw==,type:str]
    REDLIB_DEFAULT_HIDE_HLS_NOTIFICATION: ENC[AES256_GCM,data:ZLQ=,iv:hrvEQoGvf1KAkv/6wHWJZzg/n48H7EWV/Up7HlVo0/w=,tag:HUmdjIhUAN6+Net76n2IlQ==,type:str]
    REDLIB_DEFAULT_HIDE_SCORE: ENC[AES256_GCM,data:yR4K,iv:0MSHW+jjkqUYD/kICTLhOmBCJl7k1Giz7E8oo5la4BQ=,tag:6jiVhl7WX76E+eQSjke7YA==,type:str]
    REDLIB_DEFAULT_HIDE_SIDEBAR_AND_SUMMARY: ENC[AES256_GCM,data:jRsX,iv:bsSqCa2ocVSdhCh3yckac1N5NGI1Uta3ltro0PR/5Ao=,tag:y80dbLtbIAr8Vm9EFukHVA==,type:str]
    REDLIB_DEFAULT_LAYOUT: ENC[AES256_GCM,data:QjvhIHs=,iv:royC1aHfMXF9M1wbuBGAvL2uhtiSC0H/WRRBV9lR6iA=,tag:iy2zNaID5cP/XXV/scobNA==,type:str]
    REDLIB_DEFAULT_POST_SORT: ENC[AES256_GCM,data:H3Xl,iv:gIjr2kSVUsxaFVt8O9RJ7D4xXj54jsWRZD85mvTA590=,tag:BMmi7IJd55bW+xvHIFDKLg==,type:str]
    REDLIB_DEFAULT_SHOW_NSFW: ENC[AES256_GCM,data:3IM=,iv:CYbuFMToFz/KJH1b+knyAlY6NZ9pz8jBW37w3o4sHfw=,tag:L7RVWD7NX9TWzut2Uk4/Wg==,type:str]
    REDLIB_DEFAULT_SUBSCRIPTIONS: ""
    REDLIB_DEFAULT_THEME: ENC[AES256_GCM,data:pUd3HiY=,iv:u/fkKlOxm21LRjsNhHnazH5aS0kjBr/OHT0/Fhp8G54=,tag:lw3TlP7ArlxlsKXbngDOaw==,type:str]
    REDLIB_DEFAULT_USE_HLS: ENC[AES256_GCM,data:45E=,iv:U6RezKmitprQh90aQUsUvAj9Br4CRpcj6s001mMipF4=,tag:k8L68n+F/CqYbsD3wgx7qw==,type:str]
    REDLIB_DEFAULT_WIDE: ENC[AES256_GCM,data:cofa,iv:YsXOYhykvUoUlzek6uQNZrPGK0hqtksU+QThDXDMe4I=,tag:KRrz+8cueUk7lWVFGEqhrg==,type:str]
    REDLIB_PUSHSHIFT_FRONTEND: ENC[AES256_GCM,data:V1C/0GNGStzK3Fpf7hv+Huu9xz0=,iv:2LVfi+8/RWmpiKtgeRJE1JKKBZvYgR6OxyQG+NhjuDM=,tag:rghvrH10Y1QR6K4CKUoRkw==,type:str]
    REDLIB_ROBOTS_DISABLE_INDEXING: ENC[AES256_GCM,data:Pxze,iv:xQ6ndfxgI0vSEC6u/6P26r02mhHSyEVssicQKaR54c8=,tag:RrNcnmfgNeLewm9sSu4j/g==,type:str]
    REDLIB_SFW_ONLY: ENC[AES256_GCM,data:t6NZ,iv:bd9R0bcBeazlK6RR3SbFokhEai5cpGgruCy7Yly1haA=,tag:Ja73o/+9Laipj+Sg2BOI8Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtNTNOMkhrNk5UVVhZSjJj
            SVN3SHM2M0FoRWpBK0pYNTdUV2w3QkFqUTJnClBCd0dzaWxUTHNyNzA4OHBXbnND
            NjdwRXNoMHRuYnl6R0FHUzZtd2FHNE0KLS0tIEd5VHMwTWNJYVdsaEdtcmkrYnNQ
            QlhuUzVoRTVaS00yaHdVaWRrZG1XMEEKwRpbLoDqCaWgM7Zmwzw4NWAtUePm8Q1d
            I3qTY6DuKxluDp/S19FJtRgUFTkaexm7tKv3Blpu8ANuF1oPiQMtuw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ruzv8k3s30akc8tesmkg5mm92rppddq6cps2xtxvg74lt23x64uqq05d7w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-10T17:04:35Z"
    mac: ENC[AES256_GCM,data:GuQlqVjvBY0yXxDnWvWtmfh4op1q0Y3TBeEDtMbBoZ5ywGx0NKo+3pR9ZG43Q4r9pzBUur6e9lgp9SAWcJ4m2RzsiSy2AauRQGGscLMO1ZbJYjslcGj/BFPPSuxgIMuqUiKCFcSww2a46xOyleu4dsblHH0A0fzm3kn4oO0WEOo=,iv:L5H8v0p6ACK6KqfoZjsA0YPJcuEN2FL7x77QjMBPsjs=,tag:bmv7wKqbUwBa2WUt7PweVA==,type:str]
    version: 3.13.1
