apiVersion: v1
kind: Secret
metadata:
    name: cloudflared
    namespace: default
type: Opaque
data:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:H3rK+8b1QxD7ovpFldi+sbjSN9wH6Kph6AYA7Ak/3QWvtXDr5zJjghuF5ta3+yh0q0p4cMJz7x+SPHSM29t1ezGPdIkO9q1rwztLxKSBrT5fS2Fbq+oW/RyhxZIXPY61C1KWTDKHp2Mg9HdQJTGGZDuByEks2AjtoqX8Cmv6BoFZ3Wws5fxGHyA69nRnG4wZXyQ8exKwpNN8BLcBhgIAXh6jaoW3CA7JC7HDmoEx8YgtPT4RQXfmLxmXjV1ma1DCB/BNzuag1d2jEJzK2rNuJcXNa+wL4s8UWf3DxIcnwNmoGj750UPtgQxKGvA9Edqii27ZlM59EjU=,iv:K7q5aWzaO3boLeA5jxOfKRGYbRT5C/FQY2t81f4NdPQ=,tag:itxUE5IOzSW+XWmcVbYbWw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYdzNTQithNjVkRGYrNlVi
            Z3ducWQ5Mk1PZjNUQys1c3hSaXFybDBlRjNNCmNFeGVIbG9KczNGdTJqV0o5amRO
            MGJma0o4MmpTMENTbkVHQ05DRkpyb00KLS0tIDNIUmRSbnRNZTlwb1pxeXpXQW4r
            UXhaN2MrMHQrbUlFYTlGTUZWTFg5Z00KmSa2tHsv+XZJRSBreAD/gCsgliVQEiRM
            pU3eMMMmKqpDFx2NyTxAVxqQWri2PCc+MeSAlP7Epyro1Bugn4kv1w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ruzv8k3s30akc8tesmkg5mm92rppddq6cps2xtxvg74lt23x64uqq05d7w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T04:19:24Z"
    mac: ENC[AES256_GCM,data:Gi8X9+Zyu4Q/4WkbuU0JcIYPLVifUH9iTXj1oYcwNJOkfmj12GNRihYAHC2pCC19tHb59ylcqwYt/OOvtNz0eXSegJBxFUINZdDZ0iItgMA1mMNK1BuVLXD+ONnkl1H+ADSiledgTONSX5FbQO4ggENhSH7iOv3Bq8Me7nlnCNk=,iv:vCUXqi6YaS43lX+QFeEGcJUrUaXdF6LFbNsihZrZguA=,tag:LO/kCmSLfJnRnIMz5MvVug==,type:str]
    version: 3.13.3
