services:
  it-tools:
    image: corentinth/it-tools:latest
    container_name: it-tools
    restart: unless-stopped
    expose:
      - "80"

networks:
  default:
    name: xgm-network
    external: true
