services:
  wireguard:
    image: linuxserver/wireguard:latest
    container_name: wireguard
    restart: on-failure:10
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    env_file:
      - .env
    volumes:
      - "./config:/config"
      - "/lib/modules:/lib/modules"
    ports:
      - "51820:51820/udp"
    dns:
      - "172.21.0.2"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1

networks:
  default:
    name: pihole
    external: true
