apiVersion: apps/v1
kind: Deployment
metadata:
  name: dumb
  labels:
    app: dumb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dumb
  template:
    metadata:
      labels:
        app: dumb
    spec:
      containers:
        - name: dumb
          image: ghcr.io/rramiachraf/dumb:188d5f7@sha256:91bfd6b8a036a8f0c954ce5e488f9cc94ecd065b6e0992e7cfc57912778e78da
          ports:
            - containerPort: 5555
          env:
            - name: TZ
              value: America/Bogota
          resources:
            requests:
              memory: 96Mi
            limits:
              memory: 160Mi
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
