services:
  unbound:
    image: "klutchell/unbound:latest"
    container_name: unbound
    restart: unless-stopped
    hostname: "unbound"

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    depends_on: [unbound]
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    expose:
      - "80"
    volumes:
      - "./config/pihole/etc-pihole:/etc/pihole"
      - "./config/pihole/etc-dnsmasq.d:/etc/dnsmasq.d"
    environment:
      TZ: "America/Bogota"
      ServerIP: pihole  # PiHole IP
      DNS1: unbound  # Unbound IP
      DNS2: unbound  # Unbound IP
      PIHOLE_DNS_: unbound  # Unbound IP
    env_file:
      - .env
    cap_add:
      - NET_ADMIN
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`pihole.xgabrielmorales.com`)"
      - "traefik.http.routers.pihole.entrypoints=https"
      - "traefik.http.routers.pihole.tls=true"
      - "traefik.http.routers.pihole.tls.certresolver=cloudflare"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"

networks:
  default:
    name: reverse-proxy
    external: true
