apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: intel-gpu-plugin
  namespace: kube-system
  labels:
    app: intel-gpu-plugin
spec:
  selector:
    matchLabels:
      app: intel-gpu-plugin
  template:
    metadata:
      labels:
        app: intel-gpu-plugin
    spec:
      nodeSelector:
        kubernetes.io/hostname: xgm-hm
      containers:
        - name: intel-gpu-plugin
          image: intel/intel-gpu-plugin:0.36.0@sha256:2db679be62b52ac985169084ca711cab6e6c59fe543ab2ddee58163d6f8d29e0
          args: ["-shared-dev-num", "2"]
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          resources:
            requests:
              memory: 32Mi
            limits:
              memory: 64Mi
          volumeMounts:
            - name: devfs
              mountPath: /dev/dri
              readOnly: true
            - name: sysfs
              mountPath: /sys/class/drm
              readOnly: true
            - name: kubeletsockets
              mountPath: /var/lib/kubelet/device-plugins
      volumes:
        - name: devfs
          hostPath:
            path: /dev/dri
        - name: sysfs
          hostPath:
            path: /sys/class/drm
        - name: kubeletsockets
          hostPath:
            path: /var/lib/kubelet/device-plugins
