# vim: ft=yaml.docker-compose

services:
  myspeed:
    image: germannewsmaker/myspeed:1.0.9@sha256:3a3e774b3f78d930a5a962d625b99bcb3d71730bfeb4a6b93e04fd38cfe7d9a9
    hostname: myspeed
    volumes:
      - myspeed-data:/myspeed/data
    cap_drop:
      - ALL
    networks:
      - reverse-proxy-swarm
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:5216 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: any
        delay: 30s
        window: 120s
      resources:
        limits:
          memory: 256M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.myspeed.rule=Host(`speed.xgabrielmorales.com`)"
        - "traefik.http.routers.myspeed.entrypoints=websecure"
        - "traefik.http.routers.myspeed.tls.certresolver=cloudflare"
        - "traefik.http.services.myspeed.loadbalancer.server.port=5216"

networks:
  reverse-proxy-swarm:
    external: true

volumes:
  myspeed-data:
