services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    name: xgm-network
    external: true
