services:
  invidious:
    image: quay.io/invidious/invidious:latest-arm64
    container_name: invidious
    restart: unless-stopped
    environment:
      INVIDIOUS_CONFIG_FILE: "/config/config.yml"
    volumes:
      - "./config/config.yml:/config/config.yml"
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/comments/jNQXAC9IVRw || exit 1
      start_period: 10s
      interval: 30s
      timeout: 5s
      retries: 2
    depends_on:
      invidious-signature-helper:
        condition: service_started
      invidious-db:
        condition: service_healthy
    expose:
      - "3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.invidious.rule=Host(`invidious.xgabrielmorales.com`)"
      - "traefik.http.routers.invidious.entrypoints=https"
      - "traefik.http.routers.invidious.tls=true"
      - "traefik.http.routers.invidious.tls.certresolver=cloudflare"
      - "traefik.http.services.invidious.loadbalancer.server.port=3000"

  invidious-signature-helper:
    image: quay.io/invidious/inv-sig-helper:latest
    container_name: invidious-signature-helper
    init: true
    command: ["--tcp", "0.0.0.0:12999"]
    environment:
      - RUST_LOG=info
    restart: unless-stopped
    cap_drop:
      - ALL
    read_only: true
    security_opt:
      - no-new-privileges:true

  invidious-db:
    image: docker.io/library/postgres:14
    container_name: invidious-db
    restart: unless-stopped
    volumes:
      - invidious-db-data:/var/lib/postgresql/data
      - ./config/sql:/config/sql
      - ./docker/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
    environment:
      POSTGRES_DB: invidious
      POSTGRES_USER: kemal
      POSTGRES_PASSWORD: kemal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      start_period: 10s
      retries: 5

volumes:
  invidious-db-data:

networks:
  default:
    name: reverse-proxy
    external: true
