apiVersion: apps/v1
kind: Deployment
metadata:
  name: firefly-db
  namespace: default
  labels:
    app: firefly-db
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: firefly-db
  template:
    metadata:
      labels:
        app: firefly-db
    spec:
      nodeSelector:
        kubernetes.io/hostname: xgm-hm
      containers:
        - name: postgres
          image: postgres:17@sha256:e38411452a464af89e5adadb8d223bf53b898d47d6ef918b2d58c08707350449
          ports:
            - containerPort: 5432
          env:
            - name: TZ
              value: America/Bogota
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: firefly-secret
                  key: FIREFLY_DB_DBNAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: firefly-secret
                  key: FIREFLY_DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: firefly-secret
                  key: FIREFLY_DB_PASSWORD
          resources:
            requests:
              memory: 64Mi
            limits:
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
              add:
                - CHOWN
                - DAC_OVERRIDE
                - FOWNER
                - SETUID
                - SETGID
          readinessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: firefly-db-data
---
apiVersion: v1
kind: Service
metadata:
  name: firefly-db
spec:
  selector:
    app: firefly-db
  ports:
    - port: 5432
      targetPort: 5432
