apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: firefly-secret
stringData:
    FIREFLY_APP_KEY: ENC[AES256_GCM,data:Ok+gjvL3jq/MY+uAkHPaiaUfY4OvK3mMGE5vSBOylXg=,iv:aEGZdgfrCqyV0r0qjtR0lulm1p7vgZDVrK843AjSm7I=,tag:wdKgk1BUVP1ll28zZwCE1Q==,type:str]
    FIREFLY_APP_PASSWORD: ENC[AES256_GCM,data:oMf9GNeWQXRriYhkt0Tz9LAC+LXVhXCnyI+tzpaucw==,iv:hgEqQwFaU0KjGEu8KkgyhYYTDq0G+sHB0biInT6ftv8=,tag:K4Kv/mQBZMcN8N3r9ibd2A==,type:str]
    FIREFLY_DB_DBNAME: ENC[AES256_GCM,data:bUYWNNblz1Dd7lEyQa8vF8RyYX8MKw7duWqRwUtRy8s=,iv:a05cmmFqjxG1+bsaaShrtflAloZwctu325vsCXAKSa4=,tag:Jri925Xf4zbKyfCkGzKs7w==,type:str]
    FIREFLY_DB_PASSWORD: ENC[AES256_GCM,data:Xlqu2Gjs7wEWVhk+QkZ0755QlZfg29MS4Gg3JdPH+4c=,iv:013rMkD4SwB0MMnKuOSxwfRlgWrlCTt0vGcRd60Cefg=,tag:2cCYVG9/e2pQ8EVmQWOX8A==,type:str]
    FIREFLY_DB_USER: ENC[AES256_GCM,data:kdIehjn1hJ1SBxBcuaBWm9HT0PBQ3NZ3poQ45wcUC6U=,iv:ev35Xu9i6tlMEzoyAxRWyGVaR1pbDnVbwsY34v6Vxns=,tag:kmzP2uRySubrt/unarrmGQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtNTNOMkhrNk5UVVhZSjJj
            SVN3SHM2M0FoRWpBK0pYNTdUV2w3QkFqUTJnClBCd0dzaWxUTHNyNzA4OHBXbnND
            NjdwRXNoMHRuYnl6R0FHUzZtd2FHNE0KLS0tIEd5VHMwTWNJYVdsaEdtcmkrYnNQ
            QlhuUzVoRTVaS00yaHdVaWRrZG1XMEEKwRpbLoDqCaWgM7Zmwzw4NWAtUePm8Q1d
            I3qTY6DuKxluDp/S19FJtRgUFTkaexm7tKv3Blpu8ANuF1oPiQMtuw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ruzv8k3s30akc8tesmkg5mm92rppddq6cps2xtxvg74lt23x64uqq05d7w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-15T01:20:22Z"
    mac: ENC[AES256_GCM,data:JY+Itf/uA1ReQ2rgU8veOsvXi4hi2+OTsWfMWH7a73DQ+ZEjRRh//ubn8yHLqFnsezYnaeixpJpjx1uI0rXUL0ROfakiDhfvjbjCEZowg26v9hX97HMqexAZz/SkqvKBLJdeKD+fk2tXHi3G38VXES2+h1VIhdgU0FTNr0zsGmk=,iv:sCuwHDkbiD3syzk2wm5nx4TVkidjSrpzsJMaFP9IZT0=,tag:KWlbA8/p4QZUiRc8JNnz9w==,type:str]
    version: 3.13.1
