api:
  dashboard: true
  insecure: true
  debug: false

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"

serversTransport:
  insecureSkipVerify: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: nginx

certificatesResolvers:
  cloudflare:
    acme:
      email: gabrielmorales1@protonmail.com
      storage: /certs/acme.json
      dnsChallenge:
        provider: cloudflare
        #disablePropagationCheck: true
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
