# vim: ft=yaml.docker-compose

services:
  clipboard:
    image: git.xgabrielmorales.com/xgabrielmorales/clipboard:0.0.1@sha256:fecbf6619f2871157903bc53e2792c927bd0ce56bf0d3cf07a9210bfc85656e1
    hostname: clipboard
    read_only: true
    cap_drop:
      - ALL
    networks:
      - reverse-proxy-swarm
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.platform.arch == x86_64
      restart_policy:
        condition: any
        delay: 30s
        window: 120s
      resources:
        limits:
          memory: 128M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.text-sync.rule=Host(`clipboard.xgabrielmorales.com`)"
        - "traefik.http.routers.text-sync.entrypoints=websecure"
        - "traefik.http.routers.text-sync.tls.certresolver=cloudflare"
        - "traefik.http.services.text-sync.loadbalancer.server.port=3000"

networks:
  reverse-proxy-swarm:
    external: true
