services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    hostname: homepage
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=pi.xgabrielmorales.com
      - HOMEPAGE_VAR_PORTAINER_URL=${HOMEPAGE_VAR_PORTAINER_URL}
      - HOMEPAGE_VAR_PORTAINER_ENV=${HOMEPAGE_VAR_PORTAINER_ENV}
      - HOMEPAGE_VAR_PORTAINTER_KEY=${HOMEPAGE_VAR_PORTAINTER_KEY}
      - HOMEPAGE_VAR_BESZEL_URL=${HOMEPAGE_VAR_BESZEL_URL}
      - HOMEPAGE_VAR_BESZEL_USERNAME=${HOMEPAGE_VAR_BESZEL_USERNAME}
      - HOMEPAGE_VAR_BESZEL_PASSWORD=${HOMEPAGE_VAR_BESZEL_PASSWORD}
      - HOMEPAGE_VAR_TRAEFIK_URL=${HOMEPAGE_VAR_TRAEFIK_URL}
      - HOMEPAGE_VAR_PIHOLE_URL=${HOMEPAGE_VAR_PIHOLE_URL}
      - HOMEPAGE_VAR_PIHOLE_KEY=${HOMEPAGE_VAR_PIHOLE_KEY}
      - HOMEPAGE_VAR_WIREGUARD_URL=${HOMEPAGE_VAR_WIREGUARD_URL}
      - HOMEPAGE_VAR_WIREGUARD_KEY=${HOMEPAGE_VAR_WIREGUARD_KEY}
      - HOMEPAGE_VAR_MYSPEED_URL=${HOMEPAGE_VAR_MYSPEED_URL}
    configs:
      - source: homepage-docker
        target: /app/config/docker.yaml
      - source: homepage-services
        target: /app/config/services.yaml
      - source: homepage-widgets
        target: /app/config/widgets.yaml
      - source: homepage-settings
        target: /app/config/settings.yaml
      - source: homepage-bookmarks
        target: /app/config/bookmarks.yaml
    networks:
      - reverse-proxy-swarm
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.node.type == xgm-mini
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.homepage.rule=Host(`pi.xgabrielmorales.com`)"
        - "traefik.http.routers.homepage.entrypoints=websecure"
        - "traefik.http.routers.homepage.tls.certresolver=cloudflare"
        - "traefik.http.services.homepage.loadbalancer.server.port=3000"

configs:
  homepage-docker:
    file: ./config/docker.yaml
  homepage-services:
    file: ./config/services.yaml
  homepage-widgets:
    file: ./config/widgets.yaml
  homepage-settings:
    file: ./config/settings.yaml
  homepage-bookmarks:
    file: ./config/bookmarks.yaml

networks:
  reverse-proxy-swarm:
    external: true
