apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  labels:
    app: cloudflared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:2026.6.1@sha256:6d91c121b803126f7a5344005d17a9324788fc09d305b6e2560ec6040a7ae283
          args:
            - tunnel
            - --no-autoupdate
            - run
          env:
            - name: TZ
              value: America/Bogota
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: forgejo
                  key: TUNNEL_TOKEN
          resources:
            limits:
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
