apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  labels:
    app: cloudflared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:2026.7.3@sha256:e39ee8da81ad5e05d77f38d2f51c60ca51bf2a8450ac3abab50c17fdb91d91bf
          args:
            - tunnel
            - --no-autoupdate
            - run
          env:
            - name: TZ
              value: America/Bogota
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: forgejo
                  key: TUNNEL_TOKEN
          resources:
            requests:
              memory: 32Mi
            limits:
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
