apiVersion: apps/v1
kind: Deployment
metadata:
  name: forgejo-db
  labels:
    app: forgejo-db
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: forgejo-db
  template:
    metadata:
      labels:
        app: forgejo-db
    spec:
      nodeSelector:
        kubernetes.io/hostname: xgm-hm
      containers:
        - name: postgres
          image: postgres:17@sha256:0af65001d05296a2ead57ac4a6412433d8913d1bb5d0c88435a7d1e1ee5cb04b
          ports:
            - containerPort: 5432
          env:
            - name: TZ
              value: America/Bogota
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: forgejo
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: forgejo
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: forgejo
                  key: POSTGRES_DATABASE
          resources:
            limits:
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
              add:
                - CHOWN
                - DAC_OVERRIDE
                - FOWNER
                - SETUID
                - SETGID
          readinessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: forgejo-db-data
---
apiVersion: v1
kind: Service
metadata:
  name: forgejo-db
spec:
  selector:
    app: forgejo-db
  ports:
    - port: 5432
      targetPort: 5432
