apiVersion: apps/v1
kind: Deployment
metadata:
  name: forgejo
  labels:
    app: forgejo
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: forgejo
  template:
    metadata:
      labels:
        app: forgejo
    spec:
      nodeSelector:
        kubernetes.io/hostname: xgm-hm
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: forgejo
          image: codeberg.org/forgejo/forgejo:15-rootless@sha256:90a7b5b335dd84dbed7f031f2721ae877c713a9226a2b246bc0ed7e1fc7dd9ec
          envFrom:
            - secretRef:
                name: forgejo
          env:
            - name: USER_UID
              value: "1000"
            - name: USER_GID
              value: "1000"
            - name: FORGEJO__database__DB_TYPE
              value: postgres
            - name: FORGEJO__database__HOST
              value: forgejo-db:5432
            - name: FORGEJO__database__NAME
              valueFrom:
                secretKeyRef:
                  name: forgejo
                  key: POSTGRES_DATABASE
            - name: FORGEJO__database__USER
              valueFrom:
                secretKeyRef:
                  name: forgejo
                  key: POSTGRES_USER
            - name: FORGEJO__database__PASSWD
              valueFrom:
                secretKeyRef:
                  name: forgejo
                  key: POSTGRES_PASSWORD
          ports:
            - name: web
              containerPort: 3000
            - name: ssh
              containerPort: 2222
              hostPort: 2222
          resources:
            requests:
              memory: 192Mi
            limits:
              memory: 320Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: data
              mountPath: /var/lib/gitea
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: forgejo-data
---
apiVersion: v1
kind: Service
metadata:
  name: forgejo
spec:
  selector:
    app: forgejo
  ports:
    - name: web
      port: 3000
      targetPort: 3000
