# vim: ft=yaml.docker-compose

services:
  traefik:
    image: traefik:v3.7.5@sha256:d6858791f9e74df44ca4014166647c41cdc2abd3bf2a71b832ca4e1c6a91b257
    hostname: traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - traefik-certs:/certs
    environment:
      - CF_DNS_API_TOKEN=${TFK_CF_DNS_API_TOKEN}
    command:
      # API and Dashboard disabled
      - "--api=false"
      # Entrypoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      # Providers
      - "--providers.swarm=true"
      - "--providers.swarm.endpoint=tcp://docker-socket-proxy:2375"
      - "--providers.swarm.exposedbydefault=false"
      - "--providers.swarm.network=reverse-proxy-swarm"
      # Certificates ACME with Cloudflare
      - "--certificatesresolvers.cloudflare.acme.storage=/certs/acme.json"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge=true"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1:53,1.0.0.1:53"
      # Logging
      - "--global.sendAnonymousUsage=false"
      - "--ping"
    healthcheck:
      test: [ "CMD", "traefik", "healthcheck", "--ping" ]
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 5
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    networks:
      - reverse-proxy-swarm
      - traefik-internal
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        delay: 30s
        window: 120s
      resources:
        limits:
          memory: 128M

  docker-socket-proxy:
    image: tecnativa/docker-socket-proxy:v0.4.2@sha256:1f3a6f303320723d199d2316a3e82b2e2685d86c275d5e3deeaf182573b47476
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      NETWORKS: 1
      NODES: 1
      SERVICES: 1
      TASKS: 1
    cap_drop:
      - ALL
    networks:
      - traefik-internal
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        delay: 30s
        window: 120s
      resources:
        limits:
          memory: 64M

volumes:
  traefik-certs:

networks:
  reverse-proxy-swarm:
    external: true
  traefik-internal:
    internal: true
