# vim: ft=yaml.docker-compose

services:
  traefik:
    image: traefik:v3.7.1@sha256:09d3ef496d61fd830905fce5035c8a9505c2d3849632cffe13e5a43b34526f90
    hostname: traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - traefik-certs:/certs
    environment:
      - CF_DNS_API_TOKEN=${TFK_CF_DNS_API_TOKEN}
    command:
      # API and Dashboard
      - "--api=true"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--api.debug=false"
      # Entrypoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      # Providers
      - "--providers.swarm=true"
      - "--providers.swarm.exposedbydefault=false"
      - "--providers.swarm.network=reverse-proxy-swarm"
      # Certificates ACME with Cloudflare
      - "--certificatesresolvers.cloudflare.acme.storage=/certs/acme.json"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge=true"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1:53,1.0.0.1:53"
      # Logging
      - "--accesslog=true"
      - "--global.sendAnonymousUsage=false"
      - "--log.level=INFO"
      - "--ping"
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - reverse-proxy-swarm
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        delay: 30s
        window: 120s
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.traefik.rule=Host(`traefik.xgabrielmorales.com`)"
        - "traefik.http.routers.traefik.entrypoints=websecure"
        - "traefik.http.routers.traefik.tls.certresolver=cloudflare"
        - "traefik.http.routers.traefik.service=api@internal"
        - "traefik.http.services.traefik.loadbalancer.server.port=8080"

volumes:
  traefik-certs:
    driver: local

networks:
  reverse-proxy-swarm:
    external: true
