services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    restart: unless-stopped
    expose:
      - "80"
    env_file:
      - .env
    volumes:
      - /path/to/data:/config
      - /path/to-custom-ssl-keys:/config/keys
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.speedtest-tracker.rule=Host(`speedtest.xgabrielmorales.com`)"
      - "traefik.http.routers.speedtest-tracker.entrypoints=https"
      - "traefik.http.routers.speedtest-tracker.tls=true"
      - "traefik.http.routers.speedtest-tracker.tls.certresolver=cloudflare"
      - "traefik.http.services.speedtest-tracker.loadbalancer.server.port=80"

networks:
  default:
    name: reverse-proxy
    external: true
