apiVersion: apps/v1
kind: Deployment
metadata:
  name: flexget
  labels:
    app: flexget
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: flexget
  template:
    metadata:
      labels:
        app: flexget
    spec:
      nodeSelector:
      containers:
        - name: flexget
          image: wiserain/flexget:3.20.10@sha256:5dcf4d5bd40c5ab37c5e1c33566588ba8b79a47b8b7688476ad0a6f13f608a69
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: America/Bogota
            - name: TORRENT_PLUGIN
              value: qbittorrent
            - name: FG_WEBUI_PASSWD
              value: ""
          resources:
            requests:
              memory: 224Mi
            limits:
              memory: 384Mi
          volumeMounts:
            - name: config
              mountPath: /config
            - name: data
              mountPath: /data
            - name: conf
              mountPath: /config/config.yml
              subPath: config.yml
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: flexget-config
        - name: data
          persistentVolumeClaim:
            claimName: media-downloads
        - name: conf
          configMap:
            name: flexget-conf
