apiVersion: apps/v1
kind: Deployment
metadata:
  name: flexget
  labels:
    app: flexget
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: flexget
  template:
    metadata:
      labels:
        app: flexget
    spec:
      nodeSelector:
        kubernetes.io/hostname: xgm-hm
      containers:
        - name: flexget
          image: wiserain/flexget:3.20.2@sha256:8276b4d41b6880e06aff92b10fa2122d429e180a4179e69db3e080348f587833
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: America/Bogota
            - name: TORRENT_PLUGIN
              value: qbittorrent
            - name: FG_WEBUI_PASSWD
              value: ""
          resources:
            requests:
              memory: 224Mi
            limits:
              memory: 384Mi
          volumeMounts:
            - name: config
              mountPath: /config
            - name: data
              mountPath: /data
            - name: conf
              mountPath: /config/config.yml
              subPath: config.yml
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: flexget-config
        - name: data
          persistentVolumeClaim:
            claimName: media-downloads
        - name: conf
          configMap:
            name: flexget-conf
