apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - filebrowser.yaml
  - flexget.yaml
  - jellyfin.yaml
  - pvcs.yaml
  - qbittorrent.yaml
configMapGenerator:
  - name: qbittorrent-conf
    files:
      - files/qBittorrent.conf
  - name: flexget-conf
    files:
      - files/config.yml
