# vim: ft=yaml.docker-compose

services:
  glance:
    image: glanceapp/glance:v0.8.4@sha256:6df86a7e8868d1eda21f35205134b1962c422957e42a0c44d4717c8e8f741b1a
    volumes:
      - /etc/localtime:/etc/localtime:ro
    configs:
      - source: glance_config
        target: /app/config/glance.yml
      - source: home_config
        target: /app/config/home.yml
      - source: user_css
        target: /app/assets/user.css
    networks:
      - reverse-proxy-swarm
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: any
        delay: 30s
        window: 120s
      resources:
        limits:
          memory: 64M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.glance.rule=Host(`dashboard.xgabrielmorales.com`)"
        - "traefik.http.routers.glance.entrypoints=websecure"
        - "traefik.http.routers.glance.tls.certresolver=cloudflare"
        - "traefik.http.services.glance.loadbalancer.server.port=8080"

configs:
  glance_config:
    file: ./config/glance.yml
  home_config:
    file: ./config/home.yml
  user_css:
    file: ./assets/user.css

networks:
  reverse-proxy-swarm:
    external: true
