apiVersion: v1
kind: Secret
metadata:
    name: degoog
type: Opaque
stringData:
    DEGOOG_SETTINGS_PASSWORDS: ENC[AES256_GCM,data:La/slm9WGoaD8jfj7HIsxCfx8a86iG7bkQ+WVMfCR0g=,iv:2T0VjdZgQ9CEwxMwRkUcs702csKCocYZ28ly3hrPv9o=,tag:e4SFX8EehH+3M5KYXvtPJQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtNTNOMkhrNk5UVVhZSjJj
            SVN3SHM2M0FoRWpBK0pYNTdUV2w3QkFqUTJnClBCd0dzaWxUTHNyNzA4OHBXbnND
            NjdwRXNoMHRuYnl6R0FHUzZtd2FHNE0KLS0tIEd5VHMwTWNJYVdsaEdtcmkrYnNQ
            QlhuUzVoRTVaS00yaHdVaWRrZG1XMEEKwRpbLoDqCaWgM7Zmwzw4NWAtUePm8Q1d
            I3qTY6DuKxluDp/S19FJtRgUFTkaexm7tKv3Blpu8ANuF1oPiQMtuw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ruzv8k3s30akc8tesmkg5mm92rppddq6cps2xtxvg74lt23x64uqq05d7w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-11T23:13:57Z"
    mac: ENC[AES256_GCM,data:mGHQBFPVfPfl8v24pFckmdsGAlyV3qIcfsFwjjYCryGs0CftabLjXBm5DTtSgkwAvPgh6uTz46JcIZhCJ6DBiHLCBlEPClKChlQUHKxjGhZq1UcYHqA2GTwrnMXKxr4tz8OGwQnW2FQd5rAdghZQGKBLEnInfmAMOygJuLD13EI=,iv:ZyGatISCueHCun+OBQa1vqfJddfWXyD4NY/wCehfZxM=,tag:bYAt0ALdM4uqflWcXD8Hxw==,type:str]
    version: 3.13.1
