# vim: ft=yaml.docker-compose

services:
  dumb:
    image: ghcr.io/rramiachraf/dumb:188d5f7@sha256:91bfd6b8a036a8f0c954ce5e488f9cc94ecd065b6e0992e7cfc57912778e78da
    hostname: dumb
    read_only: true
    cap_drop:
      - ALL
    networks:
      - reverse-proxy-swarm
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: any
        delay: 30s
        window: 120s
      resources:
        limits:
          memory: 64M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.dumb.rule=Host(`dumb.xgabrielmorales.com`)"
        - "traefik.http.routers.dumb.entrypoints=websecure"
        - "traefik.http.routers.dumb.tls.certresolver=cloudflare"
        - "traefik.http.services.dumb.loadbalancer.server.port=5555"

networks:
  reverse-proxy-swarm:
    external: true
