services:
  tailscale:
    image: tailscale/tailscale
    container_name: tailscale
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun
    environment:
      TS_HOSTNAME: "raspberry-pi"
      TS_EXTRA_ARGS: "--advertise-exit-node"
    env_file:
      - .env
    dns:
      - "172.21.0.2"

networks:
  default:
    name: pihole
    external: true
