services:
  tailscale:
    image: tailscale/tailscale
    container_name: tailscale
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun
    env_file:
      - .env
    dns:
      - "172.21.0.2"

networks:
  default:
    name: pihole
    external: true
