services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Bogota
    volumes:
      - ./config:/config
    expose:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8384/"]
      interval: 5s
      timeout: 20s
      retries: 10
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.syncthing.rule=Host(`syncthing.xgabrielmorales.com`)"
      - "traefik.http.routers.syncthing.entrypoints=websecure"
      - "traefik.http.routers.syncthing.tls.certresolver=cloudflare"
      - "traefik.http.services.syncthing.loadbalancer.server.port=8384"

networks:
  default:
    name: reverse-proxy
    external: true
