# vim: ft=yaml.docker-compose

services:
  invidious:
    image: quay.io/invidious/invidious:2026.05.28-86c425b@sha256:7c53f6c534f01a53dfff3498fbff2e3a08d526c3c7bd7959e191c21b8c416acd
    hostname: invidious
    environment:
      INVIDIOUS_CONFIG: |
        db:
          dbname: ${INVIDIOUS_DB_DBNAME}
          user: ${INVIDIOUS_DB_USER}
          password: ${INVIDIOUS_DB_PASSWORD}
          host: invidious-db
          port: 5432
        check_tables: true
        enable_user_notifications: false
        popular_enabled: false
        default_home: <none>
        feed_menu: ["Subscriptions", "Subscriptions", "Subscriptions", "Subscriptions"]
        vr_mode: false
        continue_autoplay: false
        show_nick: false
        invidious_companion:
          - private_url: http://invidious-companion:8282/companion
            public_url: https://companion.xgabrielmorales.com/companion
        invidious_companion_key: ${INVIDIOUS_INVIDIOUS_COMPANION_KEY}
        hmac_key: ${INVIDIOUS_HMAC_KEY}
    cap_drop:
      - ALL
    networks:
      - reverse-proxy-swarm
      - invidious-internal
    depends_on:
      - invidious-companion
      - invidious-db
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/comments/jNQXAC9IVRw || exit 1
      start_period: 10s
      interval: 30s
      timeout: 5s
      retries: 2
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: any
        delay: 30s
        window: 120s
      resources:
        limits:
          memory: 512M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.invidious.rule=Host(`invidious.xgabrielmorales.com`)"
        - "traefik.http.routers.invidious.entrypoints=websecure"
        - "traefik.http.routers.invidious.tls.certresolver=cloudflare"
        - "traefik.http.services.invidious.loadbalancer.server.port=3000"

  invidious-companion:
    image: quay.io/invidious/invidious-companion:master-e1ab452@sha256:314ebe3e2ff8569557b5a619123e2c69e66275a05e368a096dac4f5d5240eadc
    hostname: invidious-companion
    environment:
      - SERVER_SECRET_KEY=${INVIDIOUS_INVIDIOUS_COMPANION_KEY}
    volumes:
      - companioncache:/var/tmp/youtubei.js:rw
    cap_drop:
      - ALL
    read_only: true
    networks:
      - reverse-proxy-swarm
      - invidious-internal
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: any
        delay: 30s
        window: 120s
      resources:
        limits:
          memory: 2G
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.compnaion.rule=Host(`companion.xgabrielmorales.com`)"
        - "traefik.http.routers.compnaion.entrypoints=websecure"
        - "traefik.http.routers.compnaion.tls.certresolver=cloudflare"
        - "traefik.http.services.compnaion.loadbalancer.server.port=8282"

  invidious-db:
    image: postgres:17@sha256:2203e6282d9e7de7c24d7da234e2a744fb325df366a3fd8ed940e8abbee39527
    hostname: invidious-db
    volumes:
      - invidious-db-data:/var/lib/postgresql/data
    configs:
      - source: invidious-init-db
        target: /docker-entrypoint-initdb.d/init-invidious-db.sh
      - source: sql-channels
        target: /config/sql/channels.sql
      - source: sql-videos
        target: /config/sql/videos.sql
      - source: sql-channel-videos
        target: /config/sql/channel_videos.sql
      - source: sql-users
        target: /config/sql/users.sql
      - source: sql-session-ids
        target: /config/sql/session_ids.sql
      - source: sql-nonces
        target: /config/sql/nonces.sql
      - source: sql-annotations
        target: /config/sql/annotations.sql
      - source: sql-playlists
        target: /config/sql/playlists.sql
      - source: sql-playlist-videos
        target: /config/sql/playlist_videos.sql
    environment:
      POSTGRES_DB: ${INVIDIOUS_DB_DBNAME}
      POSTGRES_USER: ${INVIDIOUS_DB_USER}
      POSTGRES_PASSWORD: ${INVIDIOUS_DB_PASSWORD}
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - SETUID
      - SETGID
    networks:
      - invidious-internal
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: any
        delay: 30s
        window: 120s
      resources:
        limits:
          memory: 512M
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      start_period: 10s
      retries: 5

volumes:
  invidious-db-data:
  companioncache:

configs:
  invidious-init-db:
    file: ./config/init-invidious-db.sh
  sql-channels:
    file: ./config/sql/channels.sql
  sql-videos:
    file: ./config/sql/videos.sql
  sql-channel-videos:
    file: ./config/sql/channel_videos.sql
  sql-users:
    file: ./config/sql/users.sql
  sql-session-ids:
    file: ./config/sql/session_ids.sql
  sql-nonces:
    file: ./config/sql/nonces.sql
  sql-annotations:
    file: ./config/sql/annotations.sql
  sql-playlists:
    file: ./config/sql/playlists.sql
  sql-playlist-videos:
    file: ./config/sql/playlist_videos.sql

networks:
  reverse-proxy-swarm:
    external: true
  invidious-internal:
    internal: true
