# vim: ft=yaml.docker-compose

services:
  invidious:
    image: quay.io/invidious/invidious:2026.04.13-54365c0@sha256:d1e57c4029548e00a5d4d61dac50db9bd012708e4dd73d5e0de4a9ec3efbf9be
    hostname: invidious
    environment:
      INVIDIOUS_CONFIG: |
        db:
          dbname: ${INVIDIOUS_DB_DBNAME}
          user: ${INVIDIOUS_DB_USER}
          password: ${INVIDIOUS_DB_PASSWORD}
          host: invidious-db
          port: 5432
        check_tables: true
        enable_user_notifications: false
        popular_enabled: false
        default_home: <none>
        feed_menu: ["Subscriptions", "Subscriptions", "Subscriptions", "Subscriptions"]
        vr_mode: false
        continue_autoplay: false
        show_nick: false
        invidious_companion:
          - private_url: http://invidious-companion:8282/companion
            public_url: https://companion.xgabrielmorales.com/companion
        invidious_companion_key: ${INVIDIOUS_INVIDIOUS_COMPANION_KEY}
        hmac_key: ${INVIDIOUS_HMAC_KEY}
    networks:
      - reverse-proxy-swarm
      - invidious-internal
    depends_on:
      - invidious-companion
      - invidious-db
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/comments/jNQXAC9IVRw || exit 1
      start_period: 10s
      interval: 30s
      timeout: 5s
      retries: 2
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: any
        delay: 30s
        window: 120s
      resources:
        limits:
          memory: 1G
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.invidious.rule=Host(`invidious.xgabrielmorales.com`)"
        - "traefik.http.routers.invidious.entrypoints=websecure"
        - "traefik.http.routers.invidious.tls.certresolver=cloudflare"
        - "traefik.http.services.invidious.loadbalancer.server.port=3000"

  invidious-companion:
    image: quay.io/invidious/invidious-companion:master-11cc6ac@sha256:3cae3279c8f54c3baab94af83186eed19c13e2c3a04f823ac8913a1257160e26
    hostname: invidious-companion
    environment:
      - SERVER_SECRET_KEY=${INVIDIOUS_INVIDIOUS_COMPANION_KEY}
    volumes:
      - companioncache:/var/tmp/youtubei.js:rw
    cap_drop:
      - ALL
    read_only: true
    security_opt:
      - no-new-privileges:true
    networks:
      - reverse-proxy-swarm
      - invidious-internal
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: any
        delay: 30s
        window: 120s
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.compnaion.rule=Host(`companion.xgabrielmorales.com`)"
        - "traefik.http.routers.compnaion.entrypoints=websecure"
        - "traefik.http.routers.compnaion.tls.certresolver=cloudflare"
        - "traefik.http.services.compnaion.loadbalancer.server.port=8282"

  invidious-db:
    image: postgres:14.22@sha256:ae46a8452f2c137766c9d4a62f4fe60166355ff8b00512e6c48692dbf1eed3d5
    hostname: invidious-db
    volumes:
      - invidious-db-data:/var/lib/postgresql/data
    configs:
      - source: invidious-init-db
        target: /docker-entrypoint-initdb.d/init-invidious-db.sh
      - source: sql-channels
        target: /config/sql/channels.sql
      - source: sql-videos
        target: /config/sql/videos.sql
      - source: sql-channel-videos
        target: /config/sql/channel_videos.sql
      - source: sql-users
        target: /config/sql/users.sql
      - source: sql-session-ids
        target: /config/sql/session_ids.sql
      - source: sql-nonces
        target: /config/sql/nonces.sql
      - source: sql-annotations
        target: /config/sql/annotations.sql
      - source: sql-playlists
        target: /config/sql/playlists.sql
      - source: sql-playlist-videos
        target: /config/sql/playlist_videos.sql
    environment:
      POSTGRES_DB: ${INVIDIOUS_DB_DBNAME}
      POSTGRES_USER: ${INVIDIOUS_DB_USER}
      POSTGRES_PASSWORD: ${INVIDIOUS_DB_PASSWORD}
    networks:
      - invidious-internal
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: any
        delay: 30s
        window: 120s
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      start_period: 10s
      retries: 5

volumes:
  invidious-db-data:
    driver: local
  companioncache:
    driver: local

configs:
  invidious-init-db:
    file: ./config/init-invidious-db.sh
  sql-channels:
    file: ./config/sql/channels.sql
  sql-videos:
    file: ./config/sql/videos.sql
  sql-channel-videos:
    file: ./config/sql/channel_videos.sql
  sql-users:
    file: ./config/sql/users.sql
  sql-session-ids:
    file: ./config/sql/session_ids.sql
  sql-nonces:
    file: ./config/sql/nonces.sql
  sql-annotations:
    file: ./config/sql/annotations.sql
  sql-playlists:
    file: ./config/sql/playlists.sql
  sql-playlist-videos:
    file: ./config/sql/playlist_videos.sql

networks:
  reverse-proxy-swarm:
    external: true
  invidious-internal:
    driver: overlay
    internal: true
