services:
  beszel-agent:
    image: henrygd/beszel-agent:latest
    hostname: beszel-agent-{{.Node.Hostname}}
    environment:
      - KEY=${KEY}
      - PORT=${PORT:-45876}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - reverse-proxy-swarm
    healthcheck:
      test: ["CMD", "/agent", "health"]
      interval: 120s
      start_period: 30s
      timeout: 10s
      retries: 3
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

networks:
  reverse-proxy-swarm:
    external: true
