apiVersion: apps/v1
kind: Deployment
metadata:
  name: languagetool
  labels:
    app: languagetool
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: languagetool
  template:
    metadata:
      labels:
        app: languagetool
    spec:
      nodeSelector:
      containers:
        - name: languagetool
          image: meyay/languagetool:latest@sha256:25a3a1e1212d30dfbb1f382dce118b01f845f55da419207bdeb975becb81982e
          ports:
            - containerPort: 8081
          env:
            - name: TZ
              value: America/Bogota
            - name: download_ngrams_for_langs
              value: en,es
            - name: JAVA_XMX
              value: 1536m
          resources:
            requests:
              memory: 1Gi
            limits:
              memory: 4Gi
          volumeMounts:
            - name: ngrams
              mountPath: /ngrams
      volumes:
        - name: ngrams
          persistentVolumeClaim:
            claimName: languagetool-ngrams
