services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    expose:
      - "9000"
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    name: nginx
    external: true

volumes:
  data:
