# vim: ft=yaml.docker-compose

services:
  ddns-updater:
    image: qmcgaw/ddns-updater
    hostname: ddns-updater
    environment:
      - CONFIG=${CONFIG}
      - PERIOD=${PERIOD}
      - UPDATE_COOLDOWN_PERIOD=${UPDATE_COOLDOWN_PERIOD}
      - PUBLICIP_FETCHERS=${PUBLICIP_FETCHERS}
      - PUBLICIP_HTTP_PROVIDERS=${PUBLICIP_HTTP_PROVIDERS}
      - PUBLICIPV4_HTTP_PROVIDERS=${PUBLICIPV4_HTTP_PROVIDERS}
      - PUBLICIPV6_HTTP_PROVIDERS=${PUBLICIPV6_HTTP_PROVIDERS}
      - PUBLICIP_DNS_PROVIDERS=${PUBLICIP_DNS_PROVIDERS}
      - PUBLICIP_DNS_TIMEOUT=${PUBLICIP_DNS_TIMEOUT}
      - HTTP_TIMEOUT=${HTTP_TIMEOUT}
    networks:
      - reverse-proxy-swarm
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        delay: 30s
        window: 120s
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.ddns_updater.rule=Host(`dns.xgabrielmorales.com`)"
        - "traefik.http.routers.ddns_updater.entrypoints=websecure"
        - "traefik.http.routers.ddns_updater.tls.certresolver=cloudflare"
        - "traefik.http.services.ddns_updater.loadbalancer.server.port=8000"

networks:
  reverse-proxy-swarm:
    external: true
