services:
  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel-agent-${NODE_NAME}
    restart: always
    expose:
      - "45876"
    environment:
      - KEY=${KEY}
      - PORT=${PORT:-45876}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    healthcheck:
      test: ["CMD", "/agent", "health"]
      interval: 120s

networks:
  default:
    name: reverse-proxy-swarm
    external: true
