apiVersion: apps/v1
kind: Deployment
metadata:
  name: playit
  labels:
    app: playit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playit
  template:
    metadata:
      labels:
        app: playit
    spec:
      containers:
        - name: playit
          image: ghcr.io/playit-cloud/playit-agent:1.0.10@sha256:ca4766ced6e5bcee19137337808ec8fee5867c0910ac737efbb0bb452c378521
          env:
            - name: TZ
              value: America/Bogota
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: playit
                  key: SECRET_KEY
          resources:
            requests:
              memory: 32Mi
            limits:
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
