apiVersion: apps/v1
kind: Deployment
metadata:
  name: playit
  labels:
    app: playit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playit
  template:
    metadata:
      labels:
        app: playit
    spec:
      containers:
        - name: playit
          image: ghcr.io/playit-cloud/playit-agent:1.0.12@sha256:5b7748d3e8564f1cac3d3a295a23640136fbf774c76a9509bd262d16b324b06b
          env:
            - name: TZ
              value: America/Bogota
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: playit
                  key: SECRET_KEY
          resources:
            requests:
              memory: 32Mi
            limits:
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
