apiVersion: v1
kind: Secret
metadata:
    name: playit
    namespace: default
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:Tx0PlWL2iDdwodvYIK99Mkplyd6nYtwfOb6S1aLkmgt+Z8BCiVS6HWR9i7mgOCvszDyBTiLYljsshyR1mTQm9Q==,iv:9i1Fs0IrI05hTVQm1KUaiUXjtgm+RQoujGuS1uARs38=,tag:AkTSY4WKQqd4H3J/guov7A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5NllsZ3ZVWDF5Q0t2YTFm
            Y0lHSlpDdUtmRWVpNHU5Yng5YkN0Vzl3bDN3CndTcTdjbkliSUUyUXIzNW5VcDhX
            eUliM1dkRXo3M0lub2xFYTUrTlVsZEEKLS0tIGR4ZWoxaUpxbFIrSW9TejRoNGcz
            T1E1Y21jMmh1V28ra2Y5OEdOYnVZOXcK8c2HTG+0T9JtZ7u0Be6NRNguFoGT2YUN
            HYMAtLKe35diLGHPl3frdRfoJBchWElHstHJISswxhoAvQMWDejC7A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ruzv8k3s30akc8tesmkg5mm92rppddq6cps2xtxvg74lt23x64uqq05d7w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T04:48:33Z"
    mac: ENC[AES256_GCM,data:D24MFTnBz+AeliewyYYnEQz8cwWVQbiH/uZE3YP+ywF5UV0TioX1EVGZDoqdbMfLA/8LdcJ2It+0LV0QREEN7CGojOK5SjVdWL969S80wZLzAihRHwuIdeT6mbPrfbv6uGViFwlmfWzlHDfzLNA4S4PQuQyRDasBNQQhUqH4W9Y=,iv:Lw8DP9yURMIy4AClMvmk8Aw3mNc5PCBmDvfruo5reZw=,tag:YIbU5PXqpQzl+NcJKhBrmg==,type:str]
    version: 3.13.3
