apiVersion: v1
data:
    CONFIG: ENC[AES256_GCM,data:ywLp8XQd4lF/pXnwu3UjNyQBN+x/I2DLqbwg2m01tAP5vRZk3RnILkn5QSdGV5UEM/V3/5aNadrsjpajoEykbtGjNl9R/0N4yM83HhYwvjArWc9bhn8pBcylotBNuZ0CwrTkam4N11z9UxJcwDlThR1XOoZ+z2FiMHMqnECI9DG+A8yAMR7MLdLnqcZSkm2m4cl9waJjsFygXp48E/5Vmc5OljCT686A3Z1T0snZOOn3oVILiFzwnCmvEDcRgWQKAEPVm2PNLwn2LVq1jcVEwMGGz35Oczi+gWpzjtWDKS2jxbH3wdycl1C1Ir8242n/nnGfDLKo693lWbsXr9XFuHvp7w0cICqG6rYXyvWUZJ8s4BU4lYSAHbvfKWRHAFXO,iv:UEgjDv/5aTcGEXnZjJNiXF6jVcsQjsDv5j+jexSc9XM=,tag:O2QM6bjD9NkIu8BaXveUDg==,type:str]
    HTTP_TIMEOUT: ENC[AES256_GCM,data:L1OVeQ==,iv:6PAA7ASnDZkd8gtlTcqJHNYtmyxN8AZOPUYLWCgVd34=,tag:dfdlHphUfDIzZ/afpm1xtA==,type:str]
    PERIOD: ENC[AES256_GCM,data:ifHvMQ==,iv:b15TJYzgRyvyJkwWLzM8jf8qe4cSxofDcTGgRG2tphM=,tag:gCstoDefYG4jjYgEnGu40g==,type:str]
    PUBLICIP_DNS_PROVIDERS: ENC[AES256_GCM,data:xlZ1wQ==,iv:J8nto7OF9vccl3oDup3SU3d0DT0NLYXhYYB3GICnuSE=,tag:Yqwm559lNiLvgi2/8qg1+A==,type:str]
    PUBLICIP_DNS_TIMEOUT: ENC[AES256_GCM,data:d+KRaA==,iv:xyoUnNqwVhz18NfPMEfNt1G/L3Fp5+I78Hf0NxhSv3g=,tag:6WpEowp4iqg0ZWGREoAO9w==,type:str]
    PUBLICIP_FETCHERS: ENC[AES256_GCM,data:xpRxmw==,iv:5ON1SUsik+dx+54ozQeGmtOhlwtlUX5Gxw8F503tUsI=,tag:ENN8HrN3OiozeD8Ziscbhg==,type:str]
    PUBLICIP_HTTP_PROVIDERS: ENC[AES256_GCM,data:xxZmmA==,iv:4RCahTQL7qjRwd3KatJ3ifReFNyIjq3p9LIqq2PlcJQ=,tag:5xqHNAebAvEo9Db8kuSk4g==,type:str]
    PUBLICIPV4_HTTP_PROVIDERS: ENC[AES256_GCM,data:c87EYw==,iv:l1v0mnhvlmF2ahvdiL8dFKrnu99AdE2/New2aUsiBNA=,tag:OufjQduNUMUaaMZA+6lOhA==,type:str]
    PUBLICIPV6_HTTP_PROVIDERS: ENC[AES256_GCM,data:125KGQ==,iv:M218HSvYflpwroUNjal9casBPeCJ6UNfvKpokUbCg00=,tag:W8+bKqqrPAAO2QUxW0sMYg==,type:str]
    UPDATE_COOLDOWN_PERIOD: ENC[AES256_GCM,data:xynQQg==,iv:X8lmi0S+FjjNnljJ7zo74Zt6zXR3xUOR6MF6IK1b5tk=,tag:2R8zb6xeo3GnayAd3BpyBg==,type:str]
kind: Secret
metadata:
    name: dns-updater
    namespace: default
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaaW1TZ3JYZGJxUG4wbjRz
            TGozblJXZ21mZ2w1a2ZwR2todlQvZTdQVVJ3CnB1bENxNTVWM05VSVpoaEROUUVW
            YzFQTWQ0eGZuSVJEazBicW1xbGFHYjgKLS0tIEhtenJSSFg0KzJBRXE3bjQxcWE2
            dllYaVEwdklDMHpFZEpUWHRzaFZQWkUKmfYIZi9R7gUPV0MbOpOyCmVHe+QDmZ4e
            nk1ejtnOH+TLvsxHhOBRKSP8qoFtNpUI1j806kVw0MCnsZDaCufabA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ruzv8k3s30akc8tesmkg5mm92rppddq6cps2xtxvg74lt23x64uqq05d7w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-10T18:41:02Z"
    mac: ENC[AES256_GCM,data:W+5F/4c4ragjVlmbiDdJrOcBPqoDGuNJLKmtS71kVNAUzyvqSKJJ6HC69X+G+U0SjUyrFHQ7GIK5wB8DjDOfDEvBtBDqybevLqj9j9UDwI/l9ZlviJqo+heqzg9MWKzNMRRdOP2ZQXpzqoIvBzZhVQabz4RLXManBAEm1Pj3UO4=,iv:gIfZOmHL2oE0AFDdzP4PoUSov2AYxPMIB8oV74TvUlw=,tag:5MaNDRUqsl2m8UrzDGzEzQ==,type:str]
    version: 3.13.1
