# vim: ft=yaml.docker-compose

services:
  shepherd:
    image: containrrr/shepherd
    hostname: shepherd
    environment:
      - TZ=America/Bogota
      - SLEEP_TIME=30m
      - ROLLBACK_ON_FAILURE=true
      - IMAGE_AUTOCLEAN_LIMIT=2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
          - node.role == manager
