apiVersion: v1
data:
    DNS_SERVER_ADMIN_PASSWORD: ENC[AES256_GCM,data:5D8QT9eIrVpdxA+SZuvxf3gm6R7fareUAXKJGL1dUOQHcGloD9IVFBb1Ddo=,iv:lMOWnECcOMgXhtRdv/t3BVYLaqsTbzzDTJsubJWyi/g=,tag:cQn0lxgeLwU66GTq8ZVYGw==,type:str]
    DNS_SERVER_DOMAIN: ENC[AES256_GCM,data:l7lEcekFFzriXpCQbGqQBg==,iv:Z2OhcZNEZDTyRUJz5VHtjMgZBixIviJIBdy7tjbTv7s=,tag:vnDAwstHfeFwyhhC/ao8AA==,type:str]
    DNS_SERVER_FORWARDERS: ENC[AES256_GCM,data:DSXI/idEwrxcM233fX3FjobsOiI2XzMw,iv:0hW5DOTLggfClgENnomgzDyn+lcB7R9x1aB5GJQwDmg=,tag:SwgAsXR8EQFb9kx2gn29Rg==,type:str]
kind: Secret
metadata:
    name: technitium
    namespace: default
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpbmpyVVpFMC9pRDE2b3NL
            M2pCQUlRL2ovSUpybktMeVNYWFJETzB1SlMwClE1VE1Xcm5KTGFsRUxyUlpudlk1
            bEs0NTcyZlo3ZUZVNGxJQTcwWXV5ZVkKLS0tIGNEbnJLWXNSamd2ZFNwdjBDOXJY
            TGUzaW0zTVJhcjBvRGZ5alQ4ak1kdmsKcHfe0moFNMycefGsj4aDJd/HW9UEd2Sa
            VRf1vtelAb/hYU3r0z2w61bPu4fDL5MCf3ppl47crTrODg6RyALM7g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ruzv8k3s30akc8tesmkg5mm92rppddq6cps2xtxvg74lt23x64uqq05d7w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-11T03:44:41Z"
    mac: ENC[AES256_GCM,data:ilfNppP6ryZmZddkDlBZk//D09YhB3+Yc82hAAokU5lutYfY1vzc9lPEpya3Oqn/zp2488MsUSzrsa6QJR3CC/bpbxbee/qHQJff9VxiwlBOklmbZkXY6mEUzwJ2foalir5tqaImscjZtCbCWGshorGq+ofQfRiTAj0b4lW5z6M=,iv:sO4zAc06lULZ8onaeTs7TftBdiilmRlleYlzs+GWsV8=,tag:3nVAYrZ1oukG4Ia8leddFA==,type:str]
    version: 3.13.1
