# vim: ft=yaml.docker-compose

services:
  fourget:
    image: luuul/4get:latest
    hostname: fourget
    restart: always
    environment:
      - FOURGET_PROTO=http
      - FOURGET_SERVER_NAME=4get.ca
      - FOURGET_INSTANCES=https://4get.ca
    networks:
      - reverse-proxy-swarm
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.node.type == xgm-mini
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.fourget.rule=Host(`search.xgabrielmorales.com`)"
        - "traefik.http.routers.fourget.entrypoints=websecure"
        - "traefik.http.routers.fourget.tls.certresolver=cloudflare"
        - "traefik.http.services.fourget.loadbalancer.server.port=80"

networks:
  reverse-proxy-swarm:
    external: true
