templates:
  scan_downloads:
    filesystem:
      path: /data
      recursive: yes
      regexp: '(?i).*\.(mkv|mp4|avi|m4v|mov|wmv)$'
    seen: local

tasks:
  organize_series:
    template: scan_downloads
    regexp:
      reject:
        - 'media[/\\](Movies|Series)':
            from:
              - location
    all_series: yes
    series:
      - Avatar the Last Airbender:
          set:
            trakt_show_id: 245
    trakt_lookup: yes
    move:
      to: "/data/media/Series/{{series_name}}/Season {{series_season|pad(2)}}"
      rename: "{{series_name}} - S{{series_season|pad(2)}}E{{series_episode|pad(2)}}{% if trakt_ep_name %} - {{trakt_ep_name}}{% endif %}"
      clean_source: 100
      along:
        extensions:
          - srt
          - sub
          - ass

  organize_movies:
    template: scan_downloads
    regexp:
      reject:
        - 'media[/\\](Movies|Series)':
            from:
              - location
        - '(?i)s\d{1,2}e\d{1,2}'
        - '(?i)\b\d{1,2}x\d{2}\b'
    tmdb_lookup: yes
    if:
      - "tmdb_id is defined": accept
    move:
      to: "/data/media/Movies/{{tmdb_name}} ({{tmdb_year}})"
      rename: "{{tmdb_name}} ({{tmdb_year}})"
      clean_source: 100
      along:
        extensions:
          - srt
          - sub
          - ass

schedules:
  - tasks: "*"
    interval:
      minutes: 5
