global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: global-tasks
    dockerswarm_sd_configs:
      - host: http://docker-socket-proxy:2375
        role: tasks
    relabel_configs:
      - source_labels: [__meta_dockerswarm_service_mode]
        regex: global
        action: keep
      - source_labels: [__meta_dockerswarm_task_desired_state]
        regex: running
        action: keep
      - source_labels: [__meta_dockerswarm_network_name]
        regex: observability-internal
        action: keep
      - source_labels: [__meta_dockerswarm_service_name]
        target_label: job
      - source_labels: [__meta_dockerswarm_service_label_com_docker_stack_namespace]
        target_label: stack
      - source_labels: [__meta_dockerswarm_node_hostname]
        target_label: instance
      # Require explicit prometheus.port label
      - source_labels: [__meta_dockerswarm_service_label_prometheus_port]
        regex: \d+
        action: keep
      - source_labels: [__address__]
        regex: "([^:]+):\\d+"
        target_label: __container_ip
      - source_labels: [__container_ip, __meta_dockerswarm_service_label_prometheus_port]
        target_label: __address__
        regex: "(.+);(.+)"
        replacement: $1:$2
      # Default path /metrics
      - source_labels: [__meta_dockerswarm_service_label_prometheus_path]
        target_label: __meta_dockerswarm_service_label_prometheus_path
        regex: "()"
        replacement: "/metrics"
      - source_labels: [__meta_dockerswarm_service_label_prometheus_path]
        target_label: __metrics_path__

  - job_name: replicated-tasks
    dockerswarm_sd_configs:
      - host: http://docker-socket-proxy:2375
        role: tasks
    relabel_configs:
      - source_labels: [__meta_dockerswarm_service_mode]
        regex: replicated
        action: keep
      - source_labels: [__meta_dockerswarm_task_desired_state]
        regex: running
        action: keep
      - source_labels: [__meta_dockerswarm_network_name]
        regex: observability-internal
        action: keep
      - source_labels: [__meta_dockerswarm_service_name]
        target_label: job
      - source_labels: [__meta_dockerswarm_service_label_com_docker_stack_namespace]
        target_label: stack
      - source_labels: [__meta_dockerswarm_task_id]
        target_label: instance
      # Require explicit prometheus.port label
      - source_labels: [__meta_dockerswarm_service_label_prometheus_port]
        regex: \d+
        action: keep
      - source_labels: [__address__]
        regex: "([^:]+):\\d+"
        target_label: __container_ip
      - source_labels: [__container_ip, __meta_dockerswarm_service_label_prometheus_port]
        target_label: __address__
        regex: "(.+);(.+)"
        replacement: $1:$2
      # Default path /metrics
      - source_labels: [__meta_dockerswarm_service_label_prometheus_path]
        target_label: __meta_dockerswarm_service_label_prometheus_path
        regex: "()"
        replacement: "/metrics"
      - source_labels: [__meta_dockerswarm_service_label_prometheus_path]
        target_label: __metrics_path__
