services:
  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    restart: on-failure:10
    expose:
      - "80"
    environment:
      - TZ=America/Bogota
      - NTFY_BASE_URL=https://ntfy.xgabrielmorales.com
      - NTFY_UPSTREAM_BASE_URL=https://ntfy.sh
      - NTFY_BEHIND_PROXY=true
    command:
      - serve
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ntfy.rule=Host(`ntfy.xgabrielmorales.com`)"
      - "traefik.http.routers.ntfy.entrypoints=https"
      - "traefik.http.routers.ntfy.tls=true"
      - "traefik.http.routers.ntfy.tls.certresolver=cloudflare"
    healthcheck:
        test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
        interval: 60s
        timeout: 10s
        retries: 3
        start_period: 40s

networks:
  default:
    name: reverse-proxy
    external: true
