services:
  portainer:
    image: portainer/portainer-ce:latest
    hostname: portainer
    volumes:
      - portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - reverse-proxy-swarm
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.portainer.rule=Host(`portainer.xgabrielmorales.com`)"
        - "traefik.http.routers.portainer.entrypoints=websecure"
        - "traefik.http.routers.portainer.tls.certresolver=cloudflare"
        - "traefik.http.services.portainer.loadbalancer.server.port=9000"

volumes:
  portainer-data:
    driver: local

networks:
  reverse-proxy-swarm:
    external: true
