apiVersion: apps/v1
kind: Deployment
metadata:
  name: invidious
  labels:
    app: invidious
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invidious
  template:
    metadata:
      labels:
        app: invidious
    spec:
      enableServiceLinks: false
      containers:
        - name: invidious
          image: quay.io/invidious/invidious:2026.08.06-d6e4022@sha256:c1e219ec983eca09a722107978f710aa9349a48d7f5c02d670c11772949e6d2c
          ports:
            - containerPort: 3000
          env:
            - name: TZ
              value: America/Bogota
            - name: INVIDIOUS_CONFIG
              valueFrom:
                secretKeyRef:
                  name: invidious
                  key: INVIDIOUS_CONFIG
          resources:
            requests:
              memory: 128Mi
            limits:
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: invidious
spec:
  selector:
    app: invidious
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: invidious
spec:
  ingressClassName: traefik
  rules:
    - host: invidious.xgabrielmorales.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: invidious
                port:
                  number: 3000
