apiVersion: apps/v1
kind: Deployment
metadata:
  name: invidious
  labels:
    app: invidious
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invidious
  template:
    metadata:
      labels:
        app: invidious
    spec:
      enableServiceLinks: false
      containers:
        - name: invidious
          image: quay.io/invidious/invidious:2026.08.28-b3a3f3a@sha256:b560181805140122a53e84b760829ec76b877445ba34469928b179bae66abf8b
          ports:
            - containerPort: 3000
          env:
            - name: TZ
              value: America/Bogota
            - name: INVIDIOUS_CONFIG
              valueFrom:
                secretKeyRef:
                  name: invidious
                  key: INVIDIOUS_CONFIG
          resources:
            requests:
              memory: 128Mi
            limits:
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: invidious
spec:
  selector:
    app: invidious
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: invidious
spec:
  ingressClassName: traefik
  rules:
    - host: invidious.xgabrielmorales.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: invidious
                port:
                  number: 3000
