apiVersion: v1
data:
    INVIDIOUS_CONFIG: ENC[AES256_GCM,data:IYD1a132S5U2I4gMzDsdxv5qcniAYp1+r3ZdODBkqXnMFoUw5pOEGFfCDxTkmM66ZTrrOSah1uR0XB121mYFs/Bu2fG1H6IQAJYXYC+WfhYi5U1sPIZ+dJrZBv7iBIoGTTC6nEzetKfuAjVEZZQnpwVdFDvBgDKtgMQlp9n3Bj+TlYouvquqfZUrnY0l5geR2+t/8GMpiplSGnLUBnU2JTBFefaTlhiwkJWcQE8j8jv9+fQvoaEcTNiY4UC/QEWWY6ZGFHdVVRLPF6cuk8SBVr3quHIDJW87tEH6hJIyBmNN4jw4/Oq19KL4OYrvIdSjNqzoHlMqPa7lsa69hNMgfHXZRGZ5uSRXNmVqoI6W42VfIvvHANXae9rw0cT/XfVxnjbd/g+IMN1rQ8vJOUA3kvLg2ogIBB1ROjhjspZb82xRnRe/MkdEFgJUT3jJk6T1kccUKvXWUjkN/s6WwrcszaQNzWEduN6853bsV/4VRbnZ8QDPFziHuZreD/eX9mA0WH4keLDHRFGV879NNX4sB0iqCDjGVuSHCTMsmQbJgyChcRaPdcpY9UZs1OSs5nMmeWeLhgTY5Ju/0p9aHgZdzvllAdHjJ+3X+ASqQZ5v848cxRufJ5T+fp11fLjEQa7HuJFztChrt41dG5uBj7y1nuc3Cy4agsEMHSjGpI1eVFAVSA5e5Mdmddl11zYQUnOlnRLHDDcxxA2aFBktiqYk4cWJV0TUV58fiJKc+Owmx19S0oAB3iR6q/pTvM3PsAqFagh094rB+g6vUeEmP+9at/kI3IWm9NpRC1Gb7v+TfRzTS+42uaGNx/XTqzpDXF8ulqowT6e/PvH55ZElAagtlHeiIsLtON38tHGPMzna/q7cBBn/txCFg5+p+sgyOBy7xJUUYe/Wd8mpZW2qdvjRANvxp63Sfg7RFy9dhIaBoKt2QtPOK6okxxjjGs8=,iv:ADQBCbaix+8uw8jzSeiGWd21N3p7dBXniSr4VcEa8q4=,tag:IX8Ps/bX7OfcTJjEVcyjTA==,type:str]
    INVIDIOUS_DB_DBNAME: ENC[AES256_GCM,data:Hpbg17Itpw9ZHN1O,iv:53RpA8IjrNCk7uhK99yRtavTjpcuGx89v5pYVuOei38=,tag:4CKv7IhNq3L3VnZsvWSJKA==,type:str]
    INVIDIOUS_DB_PASSWORD: ENC[AES256_GCM,data:EYZyg9TLPVE=,iv:oLVLJA9B1Km9/v/F4+I1QqvA9k9E0I31zX1SJe5iCvU=,tag:bGwFGUZR0lPiPuLl6KOGPQ==,type:str]
    INVIDIOUS_DB_USER: ENC[AES256_GCM,data:XRui++6qeqA=,iv:24qEqN84hU60DyGX+fa2NUT1ZqxlwVNKubr1Nsbnfr0=,tag:UO3TPnvXmgIdwwmBLKHysA==,type:str]
    INVIDIOUS_HMAC_KEY: ENC[AES256_GCM,data:uNBWFrVZ+5X8oHjmtOIqnBcDl/IsG/Q5,iv:bnsQh0x154Xdh3kEtEVu/PQRXM+NR++MzgwIuUUMwM8=,tag:5KkwhMQr5KnW8r8y/cwasA==,type:str]
    INVIDIOUS_INVIDIOUS_COMPANION_KEY: ENC[AES256_GCM,data:GcOEeZmp/+DfY9xfCHztuokb/TdBuqfG,iv:mOM0t4TocJJYTvqXPK53IYLWoGev05qf631/vRAeMW0=,tag:bALIp/JvIf0wq3ZrCYYPPA==,type:str]
kind: Secret
metadata:
    name: invidious
    namespace: default
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRZGw0a0xtdlBoSXVjbW5r
            VnJnZ21HcnR4RVExTEFWSDRQSjZwdkx3Vmd3CmVkTjU4cEs4eVY2NGVMU0ZjVUtQ
            TW5CQ0dTck9QTVgwUzM3R3FrWDBNZnMKLS0tIFpXWUZrN3B3RkdrbDl1aE12UHBz
            MTlyTlJDQnlIYnRUM1psSTIybzZuMEkKnEM99psxPjn1FhHn+FWGcUMaIgKsLOin
            peQ9yb7y0/qZJiu7wzqr4wI8q3I5U00cMBMtcvJhkBF4Tjk/GX+29A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ruzv8k3s30akc8tesmkg5mm92rppddq6cps2xtxvg74lt23x64uqq05d7w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-10T19:08:44Z"
    mac: ENC[AES256_GCM,data:Z3w6PQrgwHKdLWMEyopYExUpXuWeiYPrU5nCsLIPIilQx/Ae/n8LrDIlhsUg/LtuVaJCcSN+0xyHH13vBE/CjXnRetcS8hCE92HSDdQOVNdlIutRblhVHNTRF1Eqsb1hnoB6nMgvTIumq6uWje/G90esOkInGjua23wa1ILBro4=,iv:L0RiAUK4uRlWXcJpAb4s2muhlSIm6/bN0McqMXO0UoQ=,tag:/nVQUq+rFcI6AGZOkAn+DA==,type:str]
    version: 3.13.1
