# vim: ft=yaml.docker-compose

services:
  beszel:
    image: henrygd/beszel:latest
    hostname: beszel
    volumes:
      - beszel-data:/beszel_data
    networks:
      - reverse-proxy-swarm
    healthcheck:
      test: ["CMD", "/beszel", "health", "--url", "http://localhost:8090"]
      start_period: 5s
      interval: 120s
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.node.type == xgm-mini
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.beszel.rule=Host(`beszel.xgabrielmorales.com`)"
        - "traefik.http.routers.beszel.entrypoints=websecure"
        - "traefik.http.routers.beszel.tls.certresolver=cloudflare"
        - "traefik.http.services.beszel.loadbalancer.server.port=8090"

volumes:
  beszel-data:
    driver: local

networks:
  reverse-proxy-swarm:
    external: true
