services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: on-failure:10
    expose:
      - "8090"
    volumes:
      - ./data:/beszel_data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.beszel.rule=Host(`beszel.xgabrielmorales.com`)"
      - "traefik.http.routers.beszel.entrypoints=https"
      - "traefik.http.routers.beszel.tls=true"
      - "traefik.http.routers.beszel.tls.certresolver=cloudflare"

  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel-agent
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file:
      - .env

networks:
  default:
    name: reverse-proxy
    external: true
