# vim: ft=yaml.docker-compose

services:
  apprise:
    image: caronc/apprise:v1.5.0@sha256:43673bf62faa88148298d52664b37b4860189555db0b251b54d79a3ef3a173cf
    hostname: apprise
    environment:
      - TZ=America/Bogota
      - APPRISE_STATEFUL_MODE=simple
      - APPRISE_WORKER_COUNT=1
    configs:
      - source: apprise_homelab
        target: /config/homelab.yml
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - SETUID
      - SETGID
    networks:
      - reverse-proxy-swarm
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:8000/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: any
        delay: 30s
        window: 120s
      resources:
        limits:
          memory: 256M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.apprise.rule=Host(`apprise.xgabrielmorales.com`)"
        - "traefik.http.routers.apprise.entrypoints=websecure"
        - "traefik.http.routers.apprise.tls.certresolver=cloudflare"
        - "traefik.http.services.apprise.loadbalancer.server.port=8000"

configs:
  apprise_homelab:
    file: ./config/homelab.yml

networks:
  reverse-proxy-swarm:
    external: true
