# vim: ft=yaml.docker-compose

services:
  qbittorrent:
    image: linuxserver/qbittorrent:5.2.2@sha256:dd24a5f3db32bc1425d3f8dc95e8aca8ac5a35905d798171230edf33f516d9a4
    hostname: qbittorrent
    ports:
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - qbittorrent-config:/config
      - media-downloads:/downloads
    configs:
      - source: qbittorrent-conf
        target: /config/qBittorrent/qBittorrent.conf
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Bogota
    networks:
      - reverse-proxy-swarm
      - media
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: any
        delay: 30s
        window: 120s
      resources:
        limits:
          memory: 1G
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.xgabrielmorales.com`)"
        - "traefik.http.routers.qbittorrent.entrypoints=websecure"
        - "traefik.http.routers.qbittorrent.tls.certresolver=cloudflare"
        - "traefik.http.services.qbittorrent.loadbalancer.server.port=8080"

  flexget:
    image: wiserain/flexget:3.19.25@sha256:b5692bf162ab4eb83dac5f566a17709746cd14bc95fb045ee0ccbee6f1f21aee
    hostname: flexget
    volumes:
      - flexget-config:/config
      - media-downloads:/data
    configs:
      - source: flexget-conf
        target: /config/config.yml
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=America/Bogota
      - TORRENT_PLUGIN=qbittorrent
      - FG_WEBUI_PASSWD=${FLEXGET_WEBUI_PASSWD}
    networks:
      - media
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: any
        delay: 30s
        window: 120s
      resources:
        limits:
          memory: 512M

  jellyfin:
    image: linuxserver/jellyfin:10.11.11@sha256:96d21c396f46f10578931c2941e3f2789f7087b5ab0e166afedf29e7385c6aa7
    hostname: jellyfin
    ports:
      - 8096:8096/tcp
    volumes:
      - jellyfin-config:/config
      - media-downloads:/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Bogota
    networks:
      - reverse-proxy-swarm
      - media
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: any
        delay: 30s
        window: 120s
      resources:
        limits:
          memory: 4G
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.xgabrielmorales.com`)"
        - "traefik.http.routers.jellyfin.entrypoints=websecure"
        - "traefik.http.routers.jellyfin.tls.certresolver=cloudflare"
        - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"

  filebrowser:
    image: filebrowser/filebrowser:v2-s6@sha256:6b41f1f8f12bc5359d825bf4096c17ef53d2c962a076361ea1b9b1923db7b422
    hostname: filebrowser
    volumes:
      - filebrowser-data:/srv
      - filebrowser-database:/database
      - filebrowser-config:/config
      - media-downloads:/srv/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Bogota
    networks:
      - reverse-proxy-swarm
      - media
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: any
        delay: 30s
        window: 120s
      resources:
        limits:
          memory: 256M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.filebrowser.rule=Host(`filebrowser.xgabrielmorales.com`)"
        - "traefik.http.routers.filebrowser.entrypoints=websecure"
        - "traefik.http.routers.filebrowser.tls.certresolver=cloudflare"
        - "traefik.http.services.filebrowser.loadbalancer.server.port=80"

volumes:
  qbittorrent-config:
  flexget-config:
  jellyfin-config:
  media-downloads:
  filebrowser-data:
  filebrowser-database:
  filebrowser-config:

configs:
  qbittorrent-conf:
    file: ./config/qbittorrent/config/qBittorrent/qBittorrent.conf
  flexget-conf:
    file: ./config/flexget/config.yml

networks:
  reverse-proxy-swarm:
    external: true
  media:
