services:
  myspeed:
    image: germannewsmaker/myspeed
    container_name: myspeed
    restart: on-failure:10
    expose:
      - "5216:5216"
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:5216 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.myspeed.rule=Host(`speed.xgabrielmorales.com`)"
      - "traefik.http.routers.myspeed.entrypoints=websecure"
      - "traefik.http.routers.myspeed.tls.certresolver=cloudflare"
      - "traefik.http.services.myspeed.loadbalancer.server.port=5216"
      - "traefik.http.routers.myspeed.middlewares=tinyauth"

networks:
  default:
    name: reverse-proxy
    external: true
