services:
  doco-cd:
    hostname: doco-cd
    image: ghcr.io/kimdre/doco-cd:0.94@sha256:378fd7d5fcbd9b038640dd14af7ded1686ab26b464bbbe7df880cc0563161e38
    environment:
      TZ: America/Bogota
      SOPS_AGE_KEY_FILE: /run/secrets/sops_age_key
      APPRISE_API_URL: https://apprise.xgabrielmorales.com/notify
      APPRISE_NOTIFY_URLS: ntfy://ntfy:8080/homelab
      APPRISE_NOTIFY_LEVEL: success
      POLL_CONFIG: |
        - url: https://git.xgabrielmorales.com/xgabrielmorales/homelab.git
          reference: trunk
          interval: 60
    secrets:
      - sops_age_key
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - doco-cd-data:/data
    cap_drop:
      - ALL
    healthcheck:
      test: ["CMD", "/doco-cd", "healthcheck"]
      start_period: 15s
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        delay: 30s
        window: 120s
      resources:
        limits:
          memory: 128M

volumes:
  doco-cd-data:

secrets:
  sops_age_key:
    external: true
