services:
  doco-cd:
    hostname: doco-cd
    image: ghcr.io/kimdre/doco-cd:0.91@sha256:dfe53c9c5a673b17582683798ccda0f955e81a7f995d09b7cc2ff452dfd4ede1
    environment:
      TZ: America/Bogota
      SOPS_AGE_KEY_FILE: /run/secrets/sops_age_key
      POLL_CONFIG: |
        - url: https://github.com/xgabrielmorales/homelab.git
          reference: trunk
          interval: 60
    secrets:
      - sops_age_key
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - doco-cd-data:/data
    cap_drop:
      - ALL
    healthcheck:
      test: ["CMD", "/doco-cd", "healthcheck"]
      start_period: 15s
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        delay: 30s
        window: 120s
      resources:
        limits:
          memory: 128M

volumes:
  doco-cd-data:

secrets:
  sops_age_key:
    external: true
