apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - clipboard
  - dumb
  - glance
  - degoog
  - nullboard
  - redlib
  - dns-updater
  - ntfy
  - invidious
  - media
  - wireguard
  - technitium
  - forgejo
