apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - atuin
  - clipboard
  - cloudflared
  - degoog
  - dns-updater
  - dumb
  - excalidraw
  - forgejo
  - glance
  - invidious
  - media
  - minecraft
  - myspeed
  - nullboard
  - redlib
  - technitium
  - wireguard
