server:
  assets-path: /app/assets

theme:
  background-color: 222 14 14
  primary-color: 39 67 69
  positive-color: 95 38 62
  negative-color: 355 65 65
  contrast-multiplier: 1.2

pages:
  # It's not necessary to create a new file for each page and include it, you can simply
  # put its contents here, though multiple pages are easier to manage when separated
  - $include: home.yml
