apiVersion: v1
kind: Secret
metadata:
    name: warpgate
    namespace: default
type: Opaque
stringData:
    WARPGATE_ADMIN_PASSWORD: ENC[AES256_GCM,data:L6+POYK5RK6GayFJuBSW+YrqBpmD4DYM,iv:kqpQWVJkTD73wQkwuUByp6sxXLZplEUQy6WKpJF/+rw=,tag:OJIq349Q1nvdVGs9dpAvWQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuTDBSOWRUVmZJSnBLZFZN
            Q0pIVC9nSjBwSEJrcld3a2NQcFZCMjRRTDF3CklnRmJDUEVlMnFndld2Smw5RTNk
            SnZ3bXhHQjJsaHgyMzBMdWExOFdaSEkKLS0tIFhWVS9PeG50cS83WHVzR2xnY3pr
            NldRbEV5TnNrZGNhaVg4UDUveE1GTWMKvy5z+qatEkSFFnAZilRsfwlnQmc57oaM
            nx+D4TOp1m/iTRklhz8F9LIU5qcjTPFkoF4eHPXzcaBPQv2U30BTpg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ruzv8k3s30akc8tesmkg5mm92rppddq6cps2xtxvg74lt23x64uqq05d7w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T06:53:39Z"
    mac: ENC[AES256_GCM,data:8Ma5dpVUNGwl6RqSZElHraCdciMElEJUJdQxPt0Mj/3g+vcq8GgdKtq2M7aWelFeVRQRMQ6MSCjnWKI51KBH8VeDNtjtvJYyY6fyGJFbVPvr5BwexNwREv0gDnbulP2w5P0m1BX2OATLcA7p+7LnVPP/4Z0hWIf/RR61udAnDHs=,iv:1/AbBQ5F2I/M3K6Zi9aehTmCwRqGEwC6jb4bcgQENaM=,tag:ok9+W1XcSB7xbcsFz58pWQ==,type:str]
    version: 3.13.3
