services:
  wireguard:
    image: ghcr.io/wg-easy/wg-easy:15.2.2@sha256:cf815209439101842f81d62bb25f7d66140e4cf8c100b4de5d0e84569d38732a
    container_name: wireguard
    restart: unless-stopped
    ports:
      - "51821:51821/tcp"
      - "51820:51820/udp"
    volumes:
      - "/lib/modules:/lib/modules:ro"
      - wireguard-etc:/etc/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

volumes:
  wireguard-etc:
