services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    restart: always
    depends_on:
      - pihole
      - unbound
    environment:
      - LANG=${WG_LANG:-en}
      - PORT=${WG_PORT_2:-51821}
      - WG_ALLOWED_IPS=${WG_ALLOWED_IPS}
      - WG_CONFIG_PORT=${WG_CONFIG_PORT}
      - WG_DEFAULT_ADDRESS=${WG_DEFAULT_ADDRESS}
      - WG_DEFAULT_DNS=10.8.1.3
      - WG_HOST=${WG_HOST}
      - WG_MTU=${WG_MTU}
      - WG_PORT=${WG_PORT_1:-51820}
      - WG_POST_DOWN=${WG_POST_DOWN}
      - WG_POST_UP=${WG_POST_UP}
    expose:
      - "51821:51821"
    ports:
      - "51820:51820/udp"
    volumes:
      - etc_wireguard:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      default:
      wg-easy:
        ipv4_address: 10.8.1.2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wireguard.rule=Host(`wireguard.xgabrielmorales.com`)"
      - "traefik.http.routers.wireguard.entrypoints=websecure"
      - "traefik.http.routers.wireguard.tls.certresolver=cloudflare"
      - "traefik.http.services.wireguard.loadbalancer.server.port=51821"
      - "traefik.http.routers.wireguard.middlewares=tinyauth"

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: always
    depends_on:
      - unbound
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - "./pihole/etc-pihole:/etc/pihole"
      - "./pihole/etc-dnsmasq.d:/etc/dnsmasq.d"
    environment:
      - TZ="America/Bogota"
      - ServerIP=pihole # PiHole IP
      - DNS1=unbound # Unbound IP
      - DNS2=unbound # Unbound IP
      - PIHOLE_DNS=unbound # Unbound IP
      - WEBPASSWORD=${PIH_WEBPASSWORD}
    cap_add:
      - NET_ADMIN
      - CAP_SYS_TIME
    networks:
      default:
      wg-easy:
        ipv4_address: 10.8.1.3
    healthcheck:
      test: ["CMD-SHELL", "dig +short +norecurse +retry=0 @127.0.0.1 pi.hole"]
      start_period: 10s
      start_interval: 3s
      interval: 10s
      timeout: 5s
      retries: 5
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`pihole.xgabrielmorales.com`)"
      - "traefik.http.routers.pihole.entrypoints=websecure"
      - "traefik.http.routers.pihole.tls.certresolver=cloudflare"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"

  unbound:
    image: "klutchell/unbound:latest"
    container_name: unbound
    restart: always
    hostname: "unbound"
    healthcheck:
      test: ["CMD", "drill", "@127.0.0.1", "dnssec.works"]
      start_period: 10s
      start_interval: 3s
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  etc_wireguard:

networks:
  default:
    name: reverse-proxy
    external: true

  wg-easy:
    name: wg-easy
    ipam:
      config:
        - subnet: 10.8.1.0/24
