services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    hostname: wg-easy
    environment:
      - WG_ALLOWED_IPS=${WG_ALLOWED_IPS}
      - WG_HOST=${WG_HOST}
      - WG_POST_DOWN=${WG_POST_DOWN}
      - WG_POST_UP=${WG_POST_UP}
    ports:
      - "51821:51821/tcp"
      - "51820:51820/udp"
    volumes:
      - etc-wireguard:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

volumes:
  etc-wireguard:
