apiVersion: apps/v1
kind: Deployment
metadata:
  name: atuin-db
  labels:
    app: atuin-db
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: atuin-db
  template:
    metadata:
      labels:
        app: atuin-db
    spec:
      nodeSelector:
        kubernetes.io/hostname: xgm-hm
      containers:
        - name: postgres
          image: postgres:17@sha256:67f41722b7a8cbdb868a44a4995c846eddfdc2973bccb291ce937dce88ad5675
          ports:
            - containerPort: 5432
          env:
            - name: TZ
              value: America/Bogota
            - name: POSTGRES_DB
              value: atuin
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: atuin
                  key: ATUIN_DB_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: atuin
                  key: ATUIN_DB_PASSWORD
          resources:
            requests:
              memory: 64Mi
            limits:
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
              add:
                - CHOWN
                - DAC_OVERRIDE
                - FOWNER
                - SETUID
                - SETGID
          readinessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: atuin-db-data
---
apiVersion: v1
kind: Service
metadata:
  name: atuin-db
spec:
  selector:
    app: atuin-db
  ports:
    - port: 5432
      targetPort: 5432
