apiVersion: apps/v1
kind: Deployment
metadata:
  name: atuin
  labels:
    app: atuin
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: atuin
  template:
    metadata:
      labels:
        app: atuin
    spec:
      containers:
        - name: atuin
          image: ghcr.io/atuinsh/atuin:18.18.1@sha256:8573bcd8343325e3de6f8322787881faeb9e82bee703b5969a55005b69d62e24
          args: ["server", "start"]
          ports:
            - containerPort: 8888
          env:
            - name: TZ
              value: America/Bogota
            - name: ATUIN_HOST
              value: "0.0.0.0"
            - name: ATUIN_PORT
              value: "8888"
            - name: ATUIN_OPEN_REGISTRATION
              value: "true"
            - name: ATUIN_DB_URI
              valueFrom:
                secretKeyRef:
                  name: atuin
                  key: ATUIN_DB_URI
          resources:
            requests:
              memory: 128Mi
            limits:
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          emptyDir: {}
