apiVersion: apps/v1
kind: Deployment
metadata:
  name: atuin
  labels:
    app: atuin
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: atuin
  template:
    metadata:
      labels:
        app: atuin
    spec:
      containers:
        - name: atuin
          image: ghcr.io/atuinsh/atuin:18.21.0@sha256:38c6c323c6d3864250dc345dcf9d41b7a408ee6e33a7cc3cde44b6ffe9f64a02
          args: ["start"]
          ports:
            - containerPort: 8888
          env:
            - name: TZ
              value: America/Bogota
            - name: ATUIN_HOST
              value: "0.0.0.0"
            - name: ATUIN_PORT
              value: "8888"
            - name: ATUIN_OPEN_REGISTRATION
              value: "true"
            - name: ATUIN_DB_URI
              valueFrom:
                secretKeyRef:
                  name: atuin
                  key: ATUIN_DB_URI
          resources:
            requests:
              memory: 32Mi
            limits:
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          emptyDir: {}
