apiVersion: v1
kind: Secret
metadata:
    name: atuin
    namespace: default
type: Opaque
stringData:
    ATUIN_DB_USERNAME: ENC[AES256_GCM,data:azAseE0=,iv:V14PpJiWBkTFb+P0KA1j2EDDYBsUdbsaQbMqe2Wwrxg=,tag:LjFeD2JRu59mPer8OV5/mw==,type:str]
    ATUIN_DB_PASSWORD: ENC[AES256_GCM,data:FxaKS8uwzbqrQSGTq6Smp9D20cQ439oKQvr9BZko8Q==,iv:rOhHcM2e9cB7rUiLEAsKQavne8w8hOpnrYsgpjRkNp4=,tag:dcy+gbapNw/+xTqLLGxt1g==,type:str]
    ATUIN_DB_URI: ENC[AES256_GCM,data:uU7jGHbKIOVn6E9eozIreDahh729zhDlCd737lqog5+isr/2XKMaJkwuSKm66ZKmKQ84bMuR4EihMcnWcI+k,iv:uDaQBmQ3P1Qtk4Q41UxMA8Kf+EgOz5AJsbXjKdvdPrc=,tag:91ya5NEbmjVSm6GNOJoesQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzNENrbDZCZHlyVHE2MXgv
            Z1F1amlmeFdBOFJ5bE56cnFWcUhJdGVZaFZ3CnNrQ1Z6ZzdlSjl4ZEdOMXJ2ZGQ0
            T2hQdy9oMDZOM1ZSSS9CdVFxcUJXaUUKLS0tIGl0R2lvT3JWQThFNFlQR0FkZWNT
            OVRPS0RCdS9nMEZUN1lFM2VjWU9BTW8Ku2oV2fcyKo6KNpqws4U3B4hBK/kUgB75
            x1jMoaQXFsPFhOQk2EPO5+BBiDdslTTlVhHDJ/4Ou99HJNFn5vkOkw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ruzv8k3s30akc8tesmkg5mm92rppddq6cps2xtxvg74lt23x64uqq05d7w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-30T15:58:41Z"
    mac: ENC[AES256_GCM,data:GFwGcVXkiPW/9H7jgdDQCGW6vYwnQ/JpgbseXgFQ0q8Um9oi8PJhnYOiD14eWc7cWALNSQGrcl2d2E+NV9qvx7zmjf1f/pJ7loc7XQWlf5GtwoOTJ1cwS3Q6+nw20MhAsOhY5ynj7K8fS+jA33Mi/Gz+an9sbAaKPSJpepn1C9Q=,iv:pma02VLQQvMnt1nV4NMemNGgDyOzOaxihN/N2Gv+xB4=,tag:xP+RQOhbCKXZQmyjIm9SLA==,type:str]
    version: 3.13.3
