services:
  mozhi:
    image: codeberg.org/aryak/mozhi:latest
    container_name: mozhi
    restart: unless-stopped
    expose:
      - "3000"
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/version || exit 1
      interval: 30s
      timeout: 5s
      retries: 2

networks:
  default:
    name: xgm-network
    external: true
