services:
  pairdrop:
    image: "lscr.io/linuxserver/pairdrop:latest"
    container_name: pairdrop
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pairdrop.rule=Host(`pairdrop.xgabrielmorales.com`)"
      - "traefik.http.routers.pairdrop.entrypoints=https"
      - "traefik.http.routers.pairdrop.tls=true"
      - "traefik.http.routers.pairdrop.tls.certresolver=cloudflare"
      - "traefik.http.services.pairdrop.loadbalancer.server.port=3000"

networks:
  default:
    name: reverse-proxy
    external: true
